#!/usr/bin/env python3
"""Generate the cross-language operation catalog directly from registered routes.

Run with --check in CI. Streaming endpoints remain on the native streaming APIs;
this catalog covers finite JSON/text HTTP operations, including optional features.
"""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STREAMING = {
    "a2a_a2a_rpc",
    "a2a_a2a_task_events",
    "bus_subscribe",
    "bus_consume_stream",
    "stream_stream",
    "subscribe_subscribe",
}

# Some protocol operations share one framework route because their action verb
# is encoded as a suffix on the final path segment. Keep the generated client
# catalog at the protocol-operation level while permission checks inventory the
# single route that Axum actually matches.
LOGICAL_ROUTE_VARIANTS = {
    "agent_services_peer_submission_action": [
        {
            "name": "agent_services_peer_cancel",
            "path": "/a2a/{namespace}/{tenant}/agents/{agent}/v1/tasks/{id}/peers/{target}/{skill}/submissions/{submission}:cancel",
        },
        {
            "name": "agent_services_peer_refresh",
            "path": "/a2a/{namespace}/{tenant}/agents/{agent}/v1/tasks/{id}/peers/{target}/{skill}/submissions/{submission}:refresh",
        },
    ]
}


def registered_operations():
    source = (ROOT / "crates/server/src/api/mod.rs").read_text()
    chunks = re.split(r'\.route\(\s*"', source)[1:]
    result = []
    for chunk in chunks:
        path, rest = chunk.split('"', 1)
        # Stop at the close of this route call, respecting nested calls.
        depth = 1
        end = 0
        for end, char in enumerate(rest):
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if not depth:
                    break
        for method, module, handler in re.findall(
            r"\b(get|post|put|delete|patch)\((\w+)::(\w+)\)", rest[:end]
        ):
            name = module + "_" + handler
            result.append(
                {
                    "name": name,
                    "method": method.upper(),
                    "path": path,
                    "parameters": re.findall(r"\{(\w+)\}", path),
                    "response": "stream"
                    if name in STREAMING
                    else "text"
                    if module == "prometheus"
                    else "json",
                }
            )
    assert len({x["name"] for x in result}) == len(result), "Duplicate operation names"
    return sorted(result, key=lambda x: x["name"])


def operations():
    result = []
    for operation in registered_operations():
        variants = LOGICAL_ROUTE_VARIANTS.get(operation["name"])
        if variants is None:
            result.append(operation)
            continue
        for variant in variants:
            path = variant["path"]
            result.append(
                {
                    **operation,
                    **variant,
                    "parameters": re.findall(r"\{(\w+)\}", path),
                }
            )
    assert len({x["name"] for x in result}) == len(result), "Duplicate operation names"
    return sorted(result, key=lambda x: x["name"])


def render(ops):
    finite = [o for o in ops if o["response"] != "stream"]
    files = {}
    files["clients/contract-fixtures/platform-api.json"] = (
        json.dumps({"operations": ops}, indent=2) + "\n"
    )
    py = "# Generated by scripts/sdk/platform_catalog.py. Do not edit.\nfrom enum import StrEnum\n\n\nclass PlatformOperation(StrEnum):\n"
    py += "".join(f'    {o["name"].upper()} = "{o["name"]}"\n' for o in finite)
    py += (
        "\n\nOPERATIONS = {\n"
        + "".join(
            f"    PlatformOperation.{o['name'].upper()}: ({o['method']!r}, {o['path']!r}, {tuple(o['parameters'])!r}, {o['response']!r}),\n"
            for o in finite
        )
        + "}\n"
    )
    files["clients/python/acteon_client/platform_catalog.py"] = py
    ts = "// Generated by scripts/sdk/platform_catalog.py. Do not edit.\nexport const platformOperations = {\n"
    ts += (
        "".join(f"  {o['name']}: {json.dumps(o)},\n" for o in finite)
        + "} as const;\nexport type PlatformOperation = keyof typeof platformOperations;\n"
    )
    files["clients/nodejs/src/platform_catalog.ts"] = ts
    camel = lambda s: "".join(x[0].upper() + x[1:] for x in s.split("_"))
    go = "// Code generated by scripts/sdk/platform_catalog.py; DO NOT EDIT.\npackage acteon\n\ntype PlatformOperation string\n\nconst (\n"
    go += (
        "".join(
            f'\tOp{camel(o["name"])} PlatformOperation = "{o["name"]}"\n'
            for o in finite
        )
        + ")\n\nvar platformOperations = map[PlatformOperation]platformDescriptor{\n"
    )
    go += (
        "".join(
            "\tOp"
            + camel(o["name"])
            + ": {"
            + json.dumps(o["method"])
            + ", "
            + json.dumps(o["path"])
            + ", []string{"
            + ", ".join(json.dumps(p) for p in o["parameters"])
            + "}, "
            + str(o["response"] == "text").lower()
            + "},\n"
            for o in finite
        )
        + "}\n"
    )
    files["clients/go/acteon/platform_catalog.go"] = go
    java = "// Generated by scripts/sdk/platform_catalog.py. Do not edit.\npackage com.acteon.client;\n\npublic enum PlatformOperation {\n"
    java += (
        ",\n".join(
            "    "
            + o["name"].upper()
            + "("
            + json.dumps(o["method"])
            + ", "
            + json.dumps(o["path"])
            + ", "
            + str(o["response"] == "text").lower()
            + ", new String[]{"
            + ", ".join(json.dumps(p) for p in o["parameters"])
            + "})"
            for o in finite
        )
        + ";\n"
    )
    java += """    final String method;
    final String path;
    final boolean text;
    final String[] parameters;
    PlatformOperation(String method, String path, boolean text, String[] parameters) {
        this.method = method; this.path = path; this.text = text; this.parameters = parameters;
    }
}
"""
    files["clients/java/src/main/java/com/acteon/client/PlatformOperation.java"] = java
    rust = "// Generated by scripts/sdk/platform_catalog.py. Do not edit.\n#![allow(missing_docs)]\n#[derive(Debug, Clone, Copy)]\npub enum PlatformOperation {\n"
    rust += (
        "".join("    " + camel(o["name"]) + ",\n" for o in finite)
        + "}\n#[rustfmt::skip]\nimpl PlatformOperation {\n    #[allow(clippy::too_many_lines)]\n    pub(crate) fn descriptor(self) -> (&'static str, &'static str, &'static [&'static str], bool) {\n        match self {\n"
    )
    rust += (
        "".join(
            "            Self::"
            + camel(o["name"])
            + " => ("
            + json.dumps(o["method"])
            + ", "
            + json.dumps(o["path"])
            + ", &["
            + ", ".join(json.dumps(p) for p in o["parameters"])
            + "], "
            + str(o["response"] == "text").lower()
            + "),\n"
            for o in finite
        )
        + "        }\n    }\n}\n"
    )
    files["crates/client/src/platform_catalog.rs"] = rust
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    # Compare language tokens, allowing each formatter's whitespace and quotes.
    # JSON is compared structurally; generated artifacts are formatted after generation.
    import ast

    def normalized(path, text):
        if path.endswith(".json"):
            return json.loads(text)
        if path.endswith(".py"):
            return ast.dump(ast.parse(text))
        return (
            re.sub(r"\s+", "", text)
            .replace(",}", "}")
            .replace(",]", "]")
            .replace(",)", ")")
        )

    failed = []
    for path, content in render(operations()).items():
        target = ROOT / path
        if args.check:
            if not target.exists() or normalized(
                path, target.read_text()
            ) != normalized(path, content):
                failed.append(path)
        else:
            target.write_text(content)
    if failed:
        raise SystemExit("Stale platform catalog: " + ", ".join(failed))
    print(f"Platform catalog: {len(operations())} logical operations accounted for")


if __name__ == "__main__":
    main()
