//! Generated Prometheus alerting rules.
//!
//! The exporter is deliberately generated from the sanitized configuration
//! snapshot. That keeps provider names and feature flags aligned with the
//! running server while ensuring secrets never enter the rule file.

use std::fmt::Write;

use crate::config::ConfigSnapshot;

const DEFAULT_PROVIDER_SUCCESS_RATE: f64 = 95.0;
const DEFAULT_PROVIDER_P99_LATENCY_MS: u64 = 5_000;
const RETENTION_WARNING_SECONDS: u64 = 86_400;

/// Render a Prometheus rule file for the current Acteon configuration.
#[allow(clippy::too_many_lines)]
pub fn render_alert_rules(config: &ConfigSnapshot) -> String {
    let mut out = String::with_capacity(4_096);
    out.push_str("# Generated by Acteon. Review thresholds and labels before applying.\n");
    out.push_str("groups:\n");
    out.push_str("  - name: acteon\n");
    out.push_str("    interval: 1m\n");
    out.push_str("    rules:\n");

    append_rule(
        &mut out,
        "ActeonMetricsUnavailable",
        "absent(acteon_actions_dispatched_total)",
        "5m",
        "critical",
        "Acteon metrics are unavailable",
        "The Acteon metrics endpoint has not exposed its dispatch counter for five minutes.",
        None,
    );
    append_rule(
        &mut out,
        "ActeonDispatchFailures",
        "increase(acteon_actions_failed_total[5m]) > 0",
        "10m",
        "warning",
        "Acteon dispatches are failing",
        "At least one action has failed after retries during the last five minutes.",
        None,
    );

    for provider in &config.providers {
        let provider_label = prom_label(&provider.name);
        let expr = format!(
            "acteon_provider_success_rate{{provider=\"{provider_label}\"}} < {DEFAULT_PROVIDER_SUCCESS_RATE}"
        );
        append_rule(
            &mut out,
            "ActeonProviderLowSuccessRate",
            &expr,
            "10m",
            "warning",
            &format!("Provider {} success rate is low", provider.name),
            &format!(
                "Provider {} has remained below {:.0}% success rate for ten minutes.",
                provider.name, DEFAULT_PROVIDER_SUCCESS_RATE
            ),
            Some(&provider.name),
        );

        let expr = format!(
            "acteon_provider_p99_latency_ms{{provider=\"{provider_label}\"}} > {DEFAULT_PROVIDER_P99_LATENCY_MS}"
        );
        append_rule(
            &mut out,
            "ActeonProviderHighLatency",
            &expr,
            "10m",
            "warning",
            &format!("Provider {} latency is high", provider.name),
            &format!(
                "Provider {} p99 latency has exceeded {} ms for ten minutes.",
                provider.name, DEFAULT_PROVIDER_P99_LATENCY_MS
            ),
            Some(&provider.name),
        );
    }

    if config.circuit_breaker.enabled {
        append_rule(
            &mut out,
            "ActeonCircuitBreakerTrips",
            "increase(acteon_circuit_open_total[5m]) > 0",
            "5m",
            "warning",
            "Acteon circuit breakers are opening",
            "A provider circuit breaker has rejected traffic during the last five minutes.",
            None,
        );
    }

    if config.quotas.enabled {
        append_rule(
            &mut out,
            "ActeonQuotaExceeded",
            "increase(acteon_quota_exceeded_total[5m]) > 0",
            "5m",
            "warning",
            "Acteon quota limits are being exceeded",
            "At least one action has been blocked by a tenant quota during the last five minutes.",
            None,
        );
    }

    if !config.compliance.mode.is_empty() && config.compliance.mode != "none" {
        append_rule(
            &mut out,
            "ActeonComplianceRetentionErrors",
            "increase(acteon_retention_errors_total[5m]) > 0",
            "5m",
            "critical",
            "Acteon compliance retention processing is failing",
            "The retention reaper has reported an error while compliance mode is enabled.",
            None,
        );
    }

    if config.audit.enabled
        && config
            .audit
            .ttl_seconds
            .is_some_and(|ttl| ttl > 0 && ttl < RETENTION_WARNING_SECONDS)
    {
        append_rule(
            &mut out,
            "ActeonAuditRetentionTooShort",
            &format!(
                "acteon_audit_retention_ttl_seconds > 0 and acteon_audit_retention_ttl_seconds < {RETENTION_WARNING_SECONDS}"
            ),
            "15m",
            "warning",
            "Acteon audit retention is short",
            "The configured audit retention window is less than one day.",
            None,
        );
    }

    if config.executor.dlq_enabled
        && config
            .executor
            .dlq_retention_seconds
            .is_some_and(|ttl| ttl > 0 && ttl < RETENTION_WARNING_SECONDS)
    {
        append_rule(
            &mut out,
            "ActeonDlqRetentionTooShort",
            &format!(
                "acteon_dlq_retention_ttl_seconds > 0 and acteon_dlq_retention_ttl_seconds < {RETENTION_WARNING_SECONDS}"
            ),
            "15m",
            "warning",
            "Acteon dead-letter retention is short",
            "The configured dead-letter retention window is less than one day.",
            None,
        );
    }

    out
}

#[allow(clippy::too_many_arguments)]
fn append_rule(
    out: &mut String,
    alert: &str,
    expr: &str,
    duration: &str,
    severity: &str,
    summary: &str,
    description: &str,
    provider: Option<&str>,
) {
    let _ = writeln!(out, "      - alert: {alert}");
    let _ = writeln!(out, "        expr: {}", yaml_quote(expr));
    let _ = writeln!(out, "        for: {duration}");
    out.push_str("        labels:\n");
    let _ = writeln!(out, "          severity: {severity}");
    out.push_str("          service: acteon\n");
    if let Some(provider) = provider {
        let _ = writeln!(out, "          provider: {}", yaml_quote(provider));
    }
    out.push_str("        annotations:\n");
    let _ = writeln!(out, "          summary: {}", yaml_quote(summary));
    let _ = writeln!(out, "          description: {}", yaml_quote(description));
}

fn yaml_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn prom_label(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ActeonConfig, ConfigSnapshot};

    #[test]
    fn generated_rules_follow_enabled_features() {
        let config: ActeonConfig = toml::from_str(
            r#"
                [quotas]
                enabled = true
                [circuit_breaker]
                enabled = true
                [compliance]
                mode = "soc2"
                [audit]
                enabled = true
                ttl_seconds = 3600
                [executor]
                dlq_enabled = true
                dlq_retention_seconds = 7200
                [[providers]]
                name = "email's provider"
                type = "log"
            "#,
        )
        .unwrap();
        let snapshot = ConfigSnapshot::from(&config);

        let rules = render_alert_rules(&snapshot);
        let _: serde_yaml_ng::Value = serde_yaml_ng::from_str(&rules).unwrap();
        assert!(rules.contains("ActeonProviderLowSuccessRate"));
        assert!(rules.contains("provider: 'email''s provider'"));
        assert!(rules.contains("ActeonCircuitBreakerTrips"));
        assert!(rules.contains("ActeonQuotaExceeded"));
        assert!(rules.contains("ActeonComplianceRetentionErrors"));
        assert!(rules.contains("ActeonAuditRetentionTooShort"));
        assert!(rules.contains("ActeonDlqRetentionTooShort"));
    }

    #[test]
    fn defaults_do_not_emit_optional_rules() {
        let config = ConfigSnapshot::default();
        let rules = render_alert_rules(&config);
        let _: serde_yaml_ng::Value = serde_yaml_ng::from_str(&rules).unwrap();
        assert!(rules.contains("ActeonMetricsUnavailable"));
        assert!(!rules.contains("ActeonCircuitBreakerTrips"));
        assert!(!rules.contains("ActeonAuditRetentionTooShort"));
        assert!(!rules.contains("ActeonDlqRetentionTooShort"));
    }
}
