#![allow(clippy::needless_for_each)]

use acteon_audit::{AuditPage, AuditQuery, AuditRecord};
use acteon_core::{
    Action, ActionError, ActionMetadata, ActionOutcome, AnalyticsBucket, AnalyticsInterval,
    AnalyticsMetric, AnalyticsQuery, AnalyticsResponse, AnalyticsTopEntry, OverageBehavior,
    ProviderResponse, QuotaUsage, QuotaWindow, ResponseStatus, TemplateProfileField,
};

use super::approvals::{
    ApprovalActionResponse, ApprovalQueryParams, ApprovalStatusResponse, ListApprovalsResponse,
};
use super::chains::{
    ChainCancelRequest, ChainDefinitionSummary, ChainDetailResponse, ChainHistoryResponse,
    ChainStepStatus, ChainSummary, ChainValidationErrorResponse, ListChainDefinitionsResponse,
    ListChainsResponse, StepAttemptResponse, StepHistoryEntry,
};
use super::dlq::{DlqDrainResponse, DlqEntry, DlqStatsResponse};
use super::embeddings::{SimilarityRequest, SimilarityResponse};
use super::events::{
    EventStateResponse, ListEventsResponse, TransitionRequest, TransitionResponse,
};
use super::groups::{FlushGroupResponse, GroupDetailResponse, GroupSummary, ListGroupsResponse};
use super::quotas::{
    CreateQuotaRequest, ListQuotasResponse, QuotaResponse, QuotaUsageResponse, UpdateQuotaRequest,
};
use super::recurring::{
    CreateRecurringRequest, CreateRecurringResponse, ListRecurringResponse,
    RecurringDetailResponse, RecurringLifecycleRequest, RecurringSummary, UpdateRecurringRequest,
};
use super::replay::{ReplayResult, ReplaySummary};
use super::retention::{
    CreateRetentionRequest, ListRetentionResponse, RetentionResponse, UpdateRetentionRequest,
};
use super::rules::{EvaluateRulesRequest, EvaluateRulesResponse, RuleTraceEntryResponse};
use super::schemas::{
    EmbeddingMetricsResponse, ErrorResponse, HealthResponse, MetricsResponse, ReloadRequest,
    ReloadResponse, RuleSummary, SetEnabledRequest, SetEnabledResponse,
};
use acteon_core::{
    CircuitBreakerActionResponse, CircuitBreakerStatus, ListCircuitBreakersResponse,
    ListProviderHealthResponse, ProviderHealthStatus,
};

#[derive(utoipa::OpenApi)]
#[openapi(
    info(
        title = "Acteon Gateway API",
        version = "0.1.0",
        description = "HTTP API for the Acteon action gateway. Dispatch actions, manage rules, and monitor service health.",
        license(name = "MIT")
    ),
    tags(
        (name = "Health", description = "Service health and metrics"),
        (name = "Dispatch", description = "Action dispatch through the gateway pipeline"),
        (name = "Rules", description = "Rule management and lifecycle"),
        (name = "Audit", description = "Audit trail query and lookup"),
        (name = "DLQ", description = "Dead-letter queue for failed actions"),
        (name = "Events", description = "Event lifecycle state management"),
        (name = "Groups", description = "Event group management for batched notifications"),
        (name = "Approvals", description = "Human-in-the-loop approval workflow"),
        (name = "Chains", description = "Task chain orchestration"),
        (name = "Embeddings", description = "Embedding similarity testing"),
        (name = "Circuit Breakers", description = "Circuit breaker admin operations"),
        (name = "Recurring Actions", description = "Cron-scheduled recurring action management"),
        (name = "Quotas", description = "Tenant quota policy management"),
        (name = "Retention", description = "Per-tenant data retention policy management"),
        (name = "Provider Health", description = "Per-provider health and performance monitoring"),
        (name = "Plugins", description = "WASM plugin management"),
        (name = "Templates", description = "Payload template and profile management"),
        (name = "Analytics", description = "Aggregated action analytics and metrics"),
        (name = "swarm", description = "Long-running agent-swarm runs (ambient agent provider)"),
        (name = "bus", description = "Agentic message bus (Kafka-backed topics, publish, subscribe)")
    ),
    paths(
        super::health::health,
        super::health::metrics,
        super::dispatch::dispatch,
        super::dispatch::dispatch_batch,
        super::rules::list_rules,
        super::rules::reload_rules,
        super::rules::set_rule_enabled,
        super::rules::evaluate_rules,
        super::audit::query_audit,
        super::audit::get_audit_by_action,
        super::replay::replay_action,
        super::replay::replay_audit,
        super::dlq::dlq_stats,
        super::dlq::dlq_drain,
        super::events::list_events,
        super::events::get_event,
        super::events::transition_event,
        super::groups::list_groups,
        super::groups::get_group,
        super::groups::flush_group,
        super::approvals::approve,
        super::approvals::reject,
        super::approvals::get_approval,
        super::approvals::list_approvals,
        super::chains::list_chains,
        super::chains::get_chain,
        super::chains::cancel_chain,
        super::chains::get_chain_history,
        super::chains::list_definitions,
        super::chains::get_definition,
        super::chains::put_definition,
        super::chains::delete_definition,
        super::embeddings::similarity,
        super::circuit_breakers::list_circuit_breakers,
        super::circuit_breakers::trip_circuit_breaker,
        super::circuit_breakers::reset_circuit_breaker,
        super::recurring::create_recurring,
        super::recurring::list_recurring,
        super::recurring::get_recurring,
        super::recurring::update_recurring,
        super::recurring::delete_recurring,
        super::recurring::pause_recurring,
        super::recurring::resume_recurring,
        super::quotas::create_quota,
        super::quotas::list_quotas,
        super::quotas::get_quota,
        super::quotas::update_quota,
        super::quotas::delete_quota,
        super::quotas::get_quota_usage,
        super::retention::create_retention,
        super::retention::list_retention,
        super::retention::get_retention,
        super::retention::update_retention,
        super::retention::delete_retention,
        super::provider_health::list_provider_health,
        super::prometheus::prometheus_metrics,
        super::plugins::list_plugins,
        super::plugins::unregister_plugin,
        super::templates::create_template,
        super::templates::list_templates,
        super::templates::get_template,
        super::templates::update_template,
        super::templates::delete_template,
        super::templates::create_profile,
        super::templates::list_profiles,
        super::templates::get_profile,
        super::templates::update_profile,
        super::templates::delete_profile,
        super::templates::render_preview,
        super::analytics::query_analytics,
        super::rules::rule_coverage,
        super::silences::create_silence,
        super::silences::list_silences,
        super::silences::get_silence,
        super::silences::update_silence,
        super::silences::delete_silence,
        super::time_intervals::create_time_interval,
        super::time_intervals::list_time_intervals,
        super::time_intervals::get_time_interval,
        super::time_intervals::update_time_interval,
        super::time_intervals::delete_time_interval,
        super::signing_keys::discover_signing_keys,
        super::swarm::list_swarm_runs,
        super::swarm::get_swarm_run,
        super::swarm::cancel_swarm_run,
        super::bus::create_topic,
        super::bus::list_topics,
        super::bus::delete_topic,
        super::bus::publish,
        super::bus::subscribe,
        super::bus::create_subscription,
        super::bus::list_subscriptions,
        super::bus::delete_subscription,
        super::bus::ack_subscription,
        super::bus::subscription_lag,
        super::bus::deadletter_subscription,
        super::bus::create_schema,
        super::bus::list_schemas,
        super::bus::get_subject_versions,
        super::bus::get_schema_version,
        super::bus::delete_schema_version,
        super::bus::bind_topic_schema,
        super::bus::unbind_topic_schema,
    ),
    components(schemas(
        Action, ActionOutcome, ProviderResponse, ResponseStatus, ActionError,
        ActionMetadata,
        HealthResponse, MetricsResponse, RuleSummary,
        ReloadRequest, ReloadResponse, SetEnabledRequest, SetEnabledResponse,
        ErrorResponse,
        AuditRecord, AuditQuery, AuditPage,
        DlqStatsResponse, DlqEntry, DlqDrainResponse,
        ReplayResult, ReplaySummary,
        EventStateResponse, ListEventsResponse, TransitionRequest, TransitionResponse,
        GroupSummary, ListGroupsResponse, GroupDetailResponse, FlushGroupResponse,
        ApprovalActionResponse, ApprovalStatusResponse, ApprovalQueryParams, ListApprovalsResponse,
        ChainSummary, ListChainsResponse, ChainDetailResponse, ChainStepStatus, ChainCancelRequest,
        ChainDefinitionSummary, ListChainDefinitionsResponse, ChainValidationErrorResponse,
        ChainHistoryResponse, StepHistoryEntry, StepAttemptResponse,
        SimilarityRequest, SimilarityResponse,
        EmbeddingMetricsResponse,
        CircuitBreakerStatus, ListCircuitBreakersResponse, CircuitBreakerActionResponse,
        CreateRecurringRequest, CreateRecurringResponse, ListRecurringResponse,
        RecurringDetailResponse, RecurringSummary, UpdateRecurringRequest,
        RecurringLifecycleRequest,
        CreateQuotaRequest, UpdateQuotaRequest, QuotaResponse, QuotaUsageResponse,
        ListQuotasResponse,
        QuotaWindow, OverageBehavior, QuotaUsage,
        EvaluateRulesRequest, EvaluateRulesResponse, RuleTraceEntryResponse,
        CreateRetentionRequest, UpdateRetentionRequest, RetentionResponse,
        ListRetentionResponse,
        ProviderHealthStatus, ListProviderHealthResponse,
        super::plugins::PluginSummary, super::plugins::ListPluginsResponse,
        super::templates::CreateTemplateRequest, super::templates::UpdateTemplateRequest,
        super::templates::TemplateResponse, super::templates::ListTemplatesResponse,
        super::templates::CreateProfileRequest, super::templates::UpdateProfileRequest,
        super::templates::ProfileResponse, super::templates::ListProfilesResponse,
        super::templates::RenderPreviewRequest, super::templates::RenderPreviewResponse,
        TemplateProfileField,
        AnalyticsMetric, AnalyticsInterval, AnalyticsQuery, AnalyticsResponse,
        AnalyticsBucket, AnalyticsTopEntry,
        acteon_core::coverage::CoverageQuery, acteon_core::coverage::CoverageKey,
        acteon_core::coverage::CoverageEntry, acteon_core::coverage::CoverageReport,
        acteon_core::silence::MatchOp, acteon_core::silence::SilenceMatcher,
        acteon_core::silence::Silence,
        super::silences::CreateSilenceRequest, super::silences::UpdateSilenceRequest,
        super::silences::MatcherInput, super::silences::SilenceResponse,
        super::silences::ListSilencesResponse,
        acteon_core::time_interval::TimeInterval, acteon_core::time_interval::TimeRange,
        acteon_core::time_interval::TimeOfDayRange, acteon_core::time_interval::WeekdayRange,
        acteon_core::time_interval::DayOfMonthRange, acteon_core::time_interval::MonthRange,
        acteon_core::time_interval::YearRange,
        super::time_intervals::CreateTimeIntervalRequest,
        super::time_intervals::UpdateTimeIntervalRequest,
        super::time_intervals::TimeIntervalResponse,
        super::time_intervals::ListTimeIntervalsResponse,
        super::time_intervals::TimeRangeInput, super::time_intervals::TimeOfDayInput,
        super::signing_keys::SigningKeyEntry, super::signing_keys::SigningKeysResponse,
        super::swarm::SwarmRunList, super::swarm::SwarmRunApiSnapshot,
        super::bus::CreateTopicRequest, super::bus::TopicResponse,
        super::bus::ListTopicsResponse, super::bus::PublishRequest,
        super::bus::PublishResponse,
        super::bus::CreateSubscriptionRequest, super::bus::SubscriptionResponse,
        super::bus::ListSubscriptionsResponse, super::bus::AckRequest,
        super::bus::AckResponse, super::bus::LagEntry, super::bus::LagResponse,
        super::bus::DeadLetterRequest, super::bus::DeadLetterResponse,
        super::bus::CreateSchemaRequest, super::bus::SchemaResponse,
        super::bus::ListSchemasResponse, super::bus::BindTopicSchemaRequest,
        super::bus::BindTopicSchemaResponse, super::bus::SchemaValidationErrorResponse,
        super::bus::SchemaValidationIssueDto,
    ))
)]
pub struct ApiDoc;
