use crate::{ActeonClient, Error};

impl ActeonClient {
    /// Fetch Prometheus alerting rules generated by the server configuration.
    pub async fn prometheus_alert_rules(&self) -> Result<String, Error> {
        let url = format!("{}/v1/metrics/alerts/prometheus.yaml", self.base_url);
        let response = self
            .add_auth(self.client.get(&url))
            .send()
            .await
            .map_err(|e| Error::Connection(e.to_string()))?;

        if response.status().is_success() {
            response
                .text()
                .await
                .map_err(|e| Error::Deserialization(e.to_string()))
        } else {
            Err(Error::Http {
                status: response.status().as_u16(),
                message: format!(
                    "Failed to fetch Prometheus alerting rules: {}",
                    response.status()
                ),
            })
        }
    }
}
