/**
 * Acteon Node.js/TypeScript Client
 *
 * HTTP client for the Acteon action gateway.
 *
 * @example
 * ```typescript
 * import { ActeonClient, createAction } from "@acteon/client";
 *
 * const client = new ActeonClient("http://localhost:8080");
 *
 * const action = createAction(
 *   "notifications",
 *   "tenant-1",
 *   "email",
 *   "send_notification",
 *   { to: "user@example.com", subject: "Hello" }
 * );
 *
 * const outcome = await client.dispatch(action);
 * console.log(`Outcome: ${outcome.type}`);
 * ```
 */

export { ActeonClient, type ActeonClientOptions } from "./client.js";
export {
  ActeonError,
  ConnectionError,
  HttpError,
  ApiError,
  NonRetryableError,
} from "./errors.js";
export {
  type WorkerTask,
  type WorkerTaskStatus,
  type PollTasksOptions,
  type EnqueueTaskOptions,
  parseWorkerTask,
  parseTaskListResponse,
  pollTasksBody,
  enqueueTaskBody,
  heartbeatTaskBody,
  completeTaskBody,
  failTaskBody,
} from "./queues.js";
export {
  WORKFLOW_TASK_ACTION_TYPE,
  CHILD_RESULT_SIGNAL_PREFIX,
  type WorkflowStatus,
  type WorkflowCheckpoint,
  type WorkflowExecution,
  type RecordCheckpointResponse,
  type ExecutionHistory,
  type StartWorkflowOptions,
  type ParentClosePolicy,
  type StartChildOptions,
  type WorkflowDirective,
  type WorkflowFn,
  type WorkflowTaskPayload,
  WorkflowContext,
  WorkflowExecutionNotFoundError,
  WorkflowSuspend,
  runWorkflowTask,
  parseWorkflowCheckpoint,
  parseWorkflowExecution,
  parseWorkflowExecutionListResponse,
  parseRecordCheckpointResponse,
  parseExecutionHistory,
  startWorkflowBody,
} from "./workflows.js";
export { Worker, type WorkerOptions, type TaskHandler } from "./worker.js";
export {
  type Action,
  type Attachment,
  type ActionOutcome,
  type ActionError,
  type ProviderResponse,
  type BatchResult,
  type ErrorResponse,
  type RuleInfo,
  type ReloadResult,
  type EvaluateRulesRequest,
  type SemanticMatchDetail,
  type RuleTraceEntry,
  type EvaluateRulesResponse,
  type AuditQuery,
  type AuditRecord,
  type AuditPage,
  type EventQuery,
  type EventState,
  type EventListResponse,
  type TransitionResponse,
  type GroupSummary,
  type GroupListResponse,
  type GroupDetail,
  type FlushGroupResponse,
  type ApprovalActionResponse,
  type ApprovalStatus,
  type ApprovalListResponse,
  createAction,
  type WebhookPayload,
  createWebhookAction,
  type CreateRecurringAction,
  type CreateRecurringResponse,
  type RecurringFilter,
  type RecurringSummary,
  type ListRecurringResponse,
  type RecurringDetail,
  type UpdateRecurringAction,
  type SwarmRunSnapshot,
  type SwarmRunFilter,
  type ListSwarmRunsResponse,
  type CreateQuotaRequest,
  type UpdateQuotaRequest,
  type QuotaPolicy,
  type ListQuotasResponse,
  type QuotaUsage,
  type SilenceMatcher,
  type CreateSilenceRequest,
  type UpdateSilenceRequest,
  type Silence,
  type ListSilencesResponse,
  type TimeOfDayInput,
  type NumericRange,
  type TimeRange,
  type CreateTimeIntervalRequest,
  type UpdateTimeIntervalRequest,
  type TimeInterval,
  type ListTimeIntervalsResponse,
  type CreateRetentionRequest,
  type UpdateRetentionRequest,
  type RetentionPolicy,
  type ListRetentionResponse,
  type ChainSummary,
  type ListChainsResponse,
  type ChainStepStatus,
  type ChainDetailResponse,
  type StepAttemptResponse,
  type StepHistoryEntry,
  type ChainHistoryResponse,
  type DagNode,
  type DagEdge,
  type DagResponse,
  type DlqStatsResponse,
  type DlqEntry,
  type DlqDrainResponse,
  type SseEvent,
  type SubscribeOptions,
  type StreamOptions,
  type WasmPluginConfig,
  type WasmPlugin,
  type RegisterPluginRequest,
  type ListPluginsResponse,
  type PluginInvocationRequest,
  type PluginInvocationResponse,
  type ComplianceMode,
  type ComplianceStatus,
  type HashChainVerification,
  type VerifyHashChainRequest,
  type AnalyticsQuery,
  type AnalyticsBucket,
  type AnalyticsTopEntry,
  type AnalyticsResponse,
  type CoverageKey,
  type CoverageEntry,
  type CoverageQuery,
  type CoverageReport,
} from "./models.js";

// Phase 8b: Agentic bus surface (Phases 1-6c)
export {
  type AppendBusConversationMessage,
  type BusAgent,
  type BusApprovalDecision,
  type BusApprovalDecisionResponse,
  type BusApprovalParkedReceipt,
  type BusApprovalStatus,
  type BusApprovalView,
  type BusConsumeItem,
  type BusConsumedMessage,
  type BusConversation,
  type BusLag,
  type BusLagPartition,
  type BusReplayMessage,
  type BusReplayResponse,
  type BusSchema,
  type BusStreamEndStatus,
  type BusStreamEnvelopeReceipt,
  type BusStreamItem,
  type BusSubscription,
  type BusToolEnvelopeReceipt,
  type BusToolResult,
  type BusToolResultLookup,
  type BusToolResultLookupParams,
  type BusToolResultStatus,
  type BusTopic,
  type CreateBusConversation,
  type CreateBusSubscription,
  type CreateBusTopic,
  type PostBusStreamChunk,
  type PostBusStreamEnd,
  type PostBusToolCall,
  type PostBusToolCallOutcome,
  type PostBusToolResult,
  type PublishBusMessage,
  type PublishReceipt,
  type ReconnectConfig,
  type RegisterBusAgent,
  type RegisterBusSchema,
  type SetBusAgentAdminState,
  type StreamChunkEnvelope,
  type StreamEndEnvelope,
  type StreamEndEnvelopeStatus,
} from "./bus_models.js";
export {
  A2A_PROTOCOL_VERSION,
  A2A_VERSION_HEADER,
  A2A_HEADERS,
  makeMessage,
  makePartData,
  makePartText,
  makePartUrl,
  makePushConfig,
  type MakeMessageOptions,
  type MakePushConfigOptions,
} from "./a2a.js";
