// Code generated by scripts/sdk/platform_catalog.py; DO NOT EDIT.
package acteon

type PlatformOperation string

const (
	OpA2aA2aRestMessageSend               PlatformOperation = "a2a_a2a_rest_message_send"
	OpA2aA2aRestTaskCancel                PlatformOperation = "a2a_a2a_rest_task_cancel"
	OpA2aA2aRestTaskGet                   PlatformOperation = "a2a_a2a_rest_task_get"
	OpA2aDiscoveryDeleteAgentCard         PlatformOperation = "a2a_discovery_delete_agent_card"
	OpA2aDiscoveryDiscoverAgent           PlatformOperation = "a2a_discovery_discover_agent"
	OpA2aDiscoveryGetAgentCard            PlatformOperation = "a2a_discovery_get_agent_card"
	OpA2aDiscoveryPutAgentCard            PlatformOperation = "a2a_discovery_put_agent_card"
	OpA2aPushRestDeletePushConfig         PlatformOperation = "a2a_push_rest_delete_push_config"
	OpA2aPushRestDeletePushDlq            PlatformOperation = "a2a_push_rest_delete_push_dlq"
	OpA2aPushRestGetPushConfig            PlatformOperation = "a2a_push_rest_get_push_config"
	OpA2aPushRestGetPushDlq               PlatformOperation = "a2a_push_rest_get_push_dlq"
	OpA2aPushRestListPushConfigs          PlatformOperation = "a2a_push_rest_list_push_configs"
	OpA2aPushRestListPushDlq              PlatformOperation = "a2a_push_rest_list_push_dlq"
	OpA2aPushRestSetPushConfig            PlatformOperation = "a2a_push_rest_set_push_config"
	OpAnalyticsQueryAnalytics             PlatformOperation = "analytics_query_analytics"
	OpApprovalsApprove                    PlatformOperation = "approvals_approve"
	OpApprovalsGetApproval                PlatformOperation = "approvals_get_approval"
	OpApprovalsListApprovals              PlatformOperation = "approvals_list_approvals"
	OpApprovalsReject                     PlatformOperation = "approvals_reject"
	OpAuditGetAuditByAction               PlatformOperation = "audit_get_audit_by_action"
	OpAuditQueryAudit                     PlatformOperation = "audit_query_audit"
	OpAuthIdentity                        PlatformOperation = "auth_identity"
	OpAuthLogin                           PlatformOperation = "auth_login"
	OpAuthLogout                          PlatformOperation = "auth_logout"
	OpBusAckSubscription                  PlatformOperation = "bus_ack_subscription"
	OpBusAppendConversationMessage        PlatformOperation = "bus_append_conversation_message"
	OpBusApproveBusApproval               PlatformOperation = "bus_approve_bus_approval"
	OpBusBindTopicSchema                  PlatformOperation = "bus_bind_topic_schema"
	OpBusCreateSchema                     PlatformOperation = "bus_create_schema"
	OpBusCreateSubscription               PlatformOperation = "bus_create_subscription"
	OpBusCreateTopic                      PlatformOperation = "bus_create_topic"
	OpBusDeadletterSubscription           PlatformOperation = "bus_deadletter_subscription"
	OpBusDeleteAgent                      PlatformOperation = "bus_delete_agent"
	OpBusDeleteConversation               PlatformOperation = "bus_delete_conversation"
	OpBusDeleteSchemaVersion              PlatformOperation = "bus_delete_schema_version"
	OpBusDeleteSubscription               PlatformOperation = "bus_delete_subscription"
	OpBusDeleteTopic                      PlatformOperation = "bus_delete_topic"
	OpBusGetAgent                         PlatformOperation = "bus_get_agent"
	OpBusGetBusApproval                   PlatformOperation = "bus_get_bus_approval"
	OpBusGetConversation                  PlatformOperation = "bus_get_conversation"
	OpBusGetSchemaVersion                 PlatformOperation = "bus_get_schema_version"
	OpBusGetSubjectVersions               PlatformOperation = "bus_get_subject_versions"
	OpBusHeartbeatAgent                   PlatformOperation = "bus_heartbeat_agent"
	OpBusListAgents                       PlatformOperation = "bus_list_agents"
	OpBusListBusApprovals                 PlatformOperation = "bus_list_bus_approvals"
	OpBusListConversations                PlatformOperation = "bus_list_conversations"
	OpBusListSchemas                      PlatformOperation = "bus_list_schemas"
	OpBusListSubscriptions                PlatformOperation = "bus_list_subscriptions"
	OpBusListTopics                       PlatformOperation = "bus_list_topics"
	OpBusLookupToolResult                 PlatformOperation = "bus_lookup_tool_result"
	OpBusPostStreamChunk                  PlatformOperation = "bus_post_stream_chunk"
	OpBusPostStreamEnd                    PlatformOperation = "bus_post_stream_end"
	OpBusPostToolCall                     PlatformOperation = "bus_post_tool_call"
	OpBusPostToolResult                   PlatformOperation = "bus_post_tool_result"
	OpBusPublish                          PlatformOperation = "bus_publish"
	OpBusRegisterAgent                    PlatformOperation = "bus_register_agent"
	OpBusRegisterConversation             PlatformOperation = "bus_register_conversation"
	OpBusRejectBusApproval                PlatformOperation = "bus_reject_bus_approval"
	OpBusReplayConversationMessages       PlatformOperation = "bus_replay_conversation_messages"
	OpBusSendToAgent                      PlatformOperation = "bus_send_to_agent"
	OpBusSessionsAck                      PlatformOperation = "bus_sessions_ack"
	OpBusSessionsClose                    PlatformOperation = "bus_sessions_close"
	OpBusSessionsGet                      PlatformOperation = "bus_sessions_get"
	OpBusSessionsOpen                     PlatformOperation = "bus_sessions_open"
	OpBusSessionsReceive                  PlatformOperation = "bus_sessions_receive"
	OpBusSessionsValidate                 PlatformOperation = "bus_sessions_validate"
	OpBusSetAgentAdminState               PlatformOperation = "bus_set_agent_admin_state"
	OpBusStagesControl                    PlatformOperation = "bus_stages_control"
	OpBusStagesControlAudit               PlatformOperation = "bus_stages_control_audit"
	OpBusStagesDiscard                    PlatformOperation = "bus_stages_discard"
	OpBusStagesGet                        PlatformOperation = "bus_stages_get"
	OpBusStagesList                       PlatformOperation = "bus_stages_list"
	OpBusStagesReplay                     PlatformOperation = "bus_stages_replay"
	OpBusStagesReplayAudit                PlatformOperation = "bus_stages_replay_audit"
	OpBusStagesStatus                     PlatformOperation = "bus_stages_status"
	OpBusSubscriptionLag                  PlatformOperation = "bus_subscription_lag"
	OpBusTransitionConversation           PlatformOperation = "bus_transition_conversation"
	OpBusUnbindTopicSchema                PlatformOperation = "bus_unbind_topic_schema"
	OpBusUpdateAgent                      PlatformOperation = "bus_update_agent"
	OpBusUpdateConversation               PlatformOperation = "bus_update_conversation"
	OpChainsCancelChain                   PlatformOperation = "chains_cancel_chain"
	OpChainsDeleteDefinition              PlatformOperation = "chains_delete_definition"
	OpChainsGetChain                      PlatformOperation = "chains_get_chain"
	OpChainsGetChainDag                   PlatformOperation = "chains_get_chain_dag"
	OpChainsGetChainDefinitionDag         PlatformOperation = "chains_get_chain_definition_dag"
	OpChainsGetChainHistory               PlatformOperation = "chains_get_chain_history"
	OpChainsGetDefinition                 PlatformOperation = "chains_get_definition"
	OpChainsListChains                    PlatformOperation = "chains_list_chains"
	OpChainsListDefinitions               PlatformOperation = "chains_list_definitions"
	OpChainsPutDefinition                 PlatformOperation = "chains_put_definition"
	OpCircuitBreakersListCircuitBreakers  PlatformOperation = "circuit_breakers_list_circuit_breakers"
	OpCircuitBreakersResetCircuitBreaker  PlatformOperation = "circuit_breakers_reset_circuit_breaker"
	OpCircuitBreakersTripCircuitBreaker   PlatformOperation = "circuit_breakers_trip_circuit_breaker"
	OpComplianceGetComplianceStatus       PlatformOperation = "compliance_get_compliance_status"
	OpComplianceVerifyAuditChain          PlatformOperation = "compliance_verify_audit_chain"
	OpConfigGetConfig                     PlatformOperation = "config_get_config"
	OpDispatchDispatch                    PlatformOperation = "dispatch_dispatch"
	OpDispatchDispatchBatch               PlatformOperation = "dispatch_dispatch_batch"
	OpDlqDlqDrain                         PlatformOperation = "dlq_dlq_drain"
	OpDlqDlqStats                         PlatformOperation = "dlq_dlq_stats"
	OpEmbeddingsSimilarity                PlatformOperation = "embeddings_similarity"
	OpEventsGetEvent                      PlatformOperation = "events_get_event"
	OpEventsListEvents                    PlatformOperation = "events_list_events"
	OpEventsTransitionEvent               PlatformOperation = "events_transition_event"
	OpExecutionsGetExecution              PlatformOperation = "executions_get_execution"
	OpExecutionsGetExecutionHistory       PlatformOperation = "executions_get_execution_history"
	OpExecutionsListExecutions            PlatformOperation = "executions_list_executions"
	OpExecutionsResetExecution            PlatformOperation = "executions_reset_execution"
	OpExecutionsSignalExecution           PlatformOperation = "executions_signal_execution"
	OpExecutionsUpsertExecutionAttributes PlatformOperation = "executions_upsert_execution_attributes"
	OpGovernanceInspect                   PlatformOperation = "governance_inspect"
	OpGovernanceIntervene                 PlatformOperation = "governance_intervene"
	OpGovernancePublishPermit             PlatformOperation = "governance_publish_permit"
	OpGroupsFlushGroup                    PlatformOperation = "groups_flush_group"
	OpGroupsGetGroup                      PlatformOperation = "groups_get_group"
	OpGroupsListGroups                    PlatformOperation = "groups_list_groups"
	OpHealthHealth                        PlatformOperation = "health_health"
	OpHealthMetrics                       PlatformOperation = "health_metrics"
	OpPluginsListPlugins                  PlatformOperation = "plugins_list_plugins"
	OpPluginsUnregisterPlugin             PlatformOperation = "plugins_unregister_plugin"
	OpPrometheusPrometheusAlertRules      PlatformOperation = "prometheus_prometheus_alert_rules"
	OpPrometheusPrometheusMetrics         PlatformOperation = "prometheus_prometheus_metrics"
	OpProviderHealthListProviderHealth    PlatformOperation = "provider_health_list_provider_health"
	OpQueuesCompleteTask                  PlatformOperation = "queues_complete_task"
	OpQueuesEnqueueTask                   PlatformOperation = "queues_enqueue_task"
	OpQueuesFailTask                      PlatformOperation = "queues_fail_task"
	OpQueuesGetTask                       PlatformOperation = "queues_get_task"
	OpQueuesHeartbeatTask                 PlatformOperation = "queues_heartbeat_task"
	OpQueuesListTasks                     PlatformOperation = "queues_list_tasks"
	OpQueuesPollQueue                     PlatformOperation = "queues_poll_queue"
	OpQuotasCreateQuota                   PlatformOperation = "quotas_create_quota"
	OpQuotasDeleteQuota                   PlatformOperation = "quotas_delete_quota"
	OpQuotasGetQuota                      PlatformOperation = "quotas_get_quota"
	OpQuotasGetQuotaUsage                 PlatformOperation = "quotas_get_quota_usage"
	OpQuotasListQuotas                    PlatformOperation = "quotas_list_quotas"
	OpQuotasReloadStaticQuotas            PlatformOperation = "quotas_reload_static_quotas"
	OpQuotasUpdateQuota                   PlatformOperation = "quotas_update_quota"
	OpRecurringBackfillRecurring          PlatformOperation = "recurring_backfill_recurring"
	OpRecurringCreateRecurring            PlatformOperation = "recurring_create_recurring"
	OpRecurringDeleteRecurring            PlatformOperation = "recurring_delete_recurring"
	OpRecurringGetRecurring               PlatformOperation = "recurring_get_recurring"
	OpRecurringListRecurring              PlatformOperation = "recurring_list_recurring"
	OpRecurringPauseRecurring             PlatformOperation = "recurring_pause_recurring"
	OpRecurringResumeRecurring            PlatformOperation = "recurring_resume_recurring"
	OpRecurringUpdateRecurring            PlatformOperation = "recurring_update_recurring"
	OpReplayReplayAction                  PlatformOperation = "replay_replay_action"
	OpReplayReplayAudit                   PlatformOperation = "replay_replay_audit"
	OpRetentionCreateRetention            PlatformOperation = "retention_create_retention"
	OpRetentionDeleteRetention            PlatformOperation = "retention_delete_retention"
	OpRetentionGetRetention               PlatformOperation = "retention_get_retention"
	OpRetentionListRetention              PlatformOperation = "retention_list_retention"
	OpRetentionUpdateRetention            PlatformOperation = "retention_update_retention"
	OpRulesEvaluateRules                  PlatformOperation = "rules_evaluate_rules"
	OpRulesListRules                      PlatformOperation = "rules_list_rules"
	OpRulesReloadRules                    PlatformOperation = "rules_reload_rules"
	OpRulesRuleCoverage                   PlatformOperation = "rules_rule_coverage"
	OpRulesSetRuleEnabled                 PlatformOperation = "rules_set_rule_enabled"
	OpSigningKeysDiscoverSigningKeys      PlatformOperation = "signing_keys_discover_signing_keys"
	OpSilencesCreateSilence               PlatformOperation = "silences_create_silence"
	OpSilencesDeleteSilence               PlatformOperation = "silences_delete_silence"
	OpSilencesGetSilence                  PlatformOperation = "silences_get_silence"
	OpSilencesListSilences                PlatformOperation = "silences_list_silences"
	OpSilencesUpdateSilence               PlatformOperation = "silences_update_silence"
	OpSwarmCancelSwarmRun                 PlatformOperation = "swarm_cancel_swarm_run"
	OpSwarmGetSwarmRun                    PlatformOperation = "swarm_get_swarm_run"
	OpSwarmListSwarmRuns                  PlatformOperation = "swarm_list_swarm_runs"
	OpTemplatesCreateProfile              PlatformOperation = "templates_create_profile"
	OpTemplatesCreateTemplate             PlatformOperation = "templates_create_template"
	OpTemplatesDeleteProfile              PlatformOperation = "templates_delete_profile"
	OpTemplatesDeleteTemplate             PlatformOperation = "templates_delete_template"
	OpTemplatesGetProfile                 PlatformOperation = "templates_get_profile"
	OpTemplatesGetTemplate                PlatformOperation = "templates_get_template"
	OpTemplatesListProfiles               PlatformOperation = "templates_list_profiles"
	OpTemplatesListTemplates              PlatformOperation = "templates_list_templates"
	OpTemplatesReloadStaticTemplates      PlatformOperation = "templates_reload_static_templates"
	OpTemplatesRenderPreview              PlatformOperation = "templates_render_preview"
	OpTemplatesUpdateProfile              PlatformOperation = "templates_update_profile"
	OpTemplatesUpdateTemplate             PlatformOperation = "templates_update_template"
	OpTimeIntervalsCreateTimeInterval     PlatformOperation = "time_intervals_create_time_interval"
	OpTimeIntervalsDeleteTimeInterval     PlatformOperation = "time_intervals_delete_time_interval"
	OpTimeIntervalsGetTimeInterval        PlatformOperation = "time_intervals_get_time_interval"
	OpTimeIntervalsListTimeIntervals      PlatformOperation = "time_intervals_list_time_intervals"
	OpTimeIntervalsUpdateTimeInterval     PlatformOperation = "time_intervals_update_time_interval"
	OpVerifyVerifyAction                  PlatformOperation = "verify_verify_action"
	OpWorkflowsCancelWorkflow             PlatformOperation = "workflows_cancel_workflow"
	OpWorkflowsGetWorkflow                PlatformOperation = "workflows_get_workflow"
	OpWorkflowsListWorkflows              PlatformOperation = "workflows_list_workflows"
	OpWorkflowsRecordCheckpoint           PlatformOperation = "workflows_record_checkpoint"
	OpWorkflowsSignalWorkflow             PlatformOperation = "workflows_signal_workflow"
	OpWorkflowsStartChildWorkflow         PlatformOperation = "workflows_start_child_workflow"
	OpWorkflowsStartWorkflow              PlatformOperation = "workflows_start_workflow"
	OpWorkforceChange                     PlatformOperation = "workforce_change"
	OpWorkforceInspect                    PlatformOperation = "workforce_inspect"
)

var platformOperations = map[PlatformOperation]platformDescriptor{
	OpA2aA2aRestMessageSend:               {"POST", "/a2a/{namespace}/{tenant}/v1/message:send", []string{"namespace", "tenant"}, false},
	OpA2aA2aRestTaskCancel:                {"POST", "/a2a/{namespace}/{tenant}/v1/tasks/{id}", []string{"namespace", "tenant", "id"}, false},
	OpA2aA2aRestTaskGet:                   {"GET", "/a2a/{namespace}/{tenant}/v1/tasks/{id}", []string{"namespace", "tenant", "id"}, false},
	OpA2aDiscoveryDeleteAgentCard:         {"DELETE", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/card", []string{"namespace", "tenant", "agent_id"}, false},
	OpA2aDiscoveryDiscoverAgent:           {"GET", "/a2a/{namespace}/{tenant}/.well-known/agent.json", []string{"namespace", "tenant"}, false},
	OpA2aDiscoveryGetAgentCard:            {"GET", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/card", []string{"namespace", "tenant", "agent_id"}, false},
	OpA2aDiscoveryPutAgentCard:            {"PUT", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/card", []string{"namespace", "tenant", "agent_id"}, false},
	OpA2aPushRestDeletePushConfig:         {"DELETE", "/a2a/{namespace}/{tenant}/v1/tasks/{id}/pushNotificationConfigs/{cfgId}", []string{"namespace", "tenant", "id", "cfgId"}, false},
	OpA2aPushRestDeletePushDlq:            {"DELETE", "/v1/a2a/{namespace}/{tenant}/push-dlq/{entryId}", []string{"namespace", "tenant", "entryId"}, false},
	OpA2aPushRestGetPushConfig:            {"GET", "/a2a/{namespace}/{tenant}/v1/tasks/{id}/pushNotificationConfigs/{cfgId}", []string{"namespace", "tenant", "id", "cfgId"}, false},
	OpA2aPushRestGetPushDlq:               {"GET", "/v1/a2a/{namespace}/{tenant}/push-dlq/{entryId}", []string{"namespace", "tenant", "entryId"}, false},
	OpA2aPushRestListPushConfigs:          {"GET", "/a2a/{namespace}/{tenant}/v1/tasks/{id}/pushNotificationConfigs", []string{"namespace", "tenant", "id"}, false},
	OpA2aPushRestListPushDlq:              {"GET", "/v1/a2a/{namespace}/{tenant}/push-dlq", []string{"namespace", "tenant"}, false},
	OpA2aPushRestSetPushConfig:            {"POST", "/a2a/{namespace}/{tenant}/v1/tasks/{id}/pushNotificationConfigs", []string{"namespace", "tenant", "id"}, false},
	OpAnalyticsQueryAnalytics:             {"GET", "/v1/analytics", []string{}, false},
	OpApprovalsApprove:                    {"POST", "/v1/approvals/{namespace}/{tenant}/{id}/approve", []string{"namespace", "tenant", "id"}, false},
	OpApprovalsGetApproval:                {"GET", "/v1/approvals/{namespace}/{tenant}/{id}", []string{"namespace", "tenant", "id"}, false},
	OpApprovalsListApprovals:              {"GET", "/v1/approvals", []string{}, false},
	OpApprovalsReject:                     {"POST", "/v1/approvals/{namespace}/{tenant}/{id}/reject", []string{"namespace", "tenant", "id"}, false},
	OpAuditGetAuditByAction:               {"GET", "/v1/audit/{action_id}", []string{"action_id"}, false},
	OpAuditQueryAudit:                     {"GET", "/v1/audit", []string{}, false},
	OpAuthIdentity:                        {"GET", "/v1/auth/identity", []string{}, false},
	OpAuthLogin:                           {"POST", "/v1/auth/login", []string{}, false},
	OpAuthLogout:                          {"POST", "/v1/auth/logout", []string{}, false},
	OpBusAckSubscription:                  {"POST", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/ack", []string{"namespace", "tenant", "id"}, false},
	OpBusAppendConversationMessage:        {"POST", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/messages", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusApproveBusApproval:               {"POST", "/v1/bus/approvals/{namespace}/{tenant}/{approval_id}/approve", []string{"namespace", "tenant", "approval_id"}, false},
	OpBusBindTopicSchema:                  {"PUT", "/v1/bus/topics/{namespace}/{tenant}/{name}/schema", []string{"namespace", "tenant", "name"}, false},
	OpBusCreateSchema:                     {"POST", "/v1/bus/schemas", []string{}, false},
	OpBusCreateSubscription:               {"POST", "/v1/bus/subscriptions", []string{}, false},
	OpBusCreateTopic:                      {"POST", "/v1/bus/topics", []string{}, false},
	OpBusDeadletterSubscription:           {"POST", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/deadletter", []string{"namespace", "tenant", "id"}, false},
	OpBusDeleteAgent:                      {"DELETE", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}", []string{"namespace", "tenant", "agent_id"}, false},
	OpBusDeleteConversation:               {"DELETE", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusDeleteSchemaVersion:              {"DELETE", "/v1/bus/schemas/{namespace}/{tenant}/{subject}/{version}", []string{"namespace", "tenant", "subject", "version"}, false},
	OpBusDeleteSubscription:               {"DELETE", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}", []string{"namespace", "tenant", "id"}, false},
	OpBusDeleteTopic:                      {"DELETE", "/v1/bus/topics/{kafka_name}", []string{"kafka_name"}, false},
	OpBusGetAgent:                         {"GET", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}", []string{"namespace", "tenant", "agent_id"}, false},
	OpBusGetBusApproval:                   {"GET", "/v1/bus/approvals/{namespace}/{tenant}/{approval_id}", []string{"namespace", "tenant", "approval_id"}, false},
	OpBusGetConversation:                  {"GET", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusGetSchemaVersion:                 {"GET", "/v1/bus/schemas/{namespace}/{tenant}/{subject}/{version}", []string{"namespace", "tenant", "subject", "version"}, false},
	OpBusGetSubjectVersions:               {"GET", "/v1/bus/schemas/{namespace}/{tenant}/{subject}", []string{"namespace", "tenant", "subject"}, false},
	OpBusHeartbeatAgent:                   {"POST", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/heartbeat", []string{"namespace", "tenant", "agent_id"}, false},
	OpBusListAgents:                       {"GET", "/v1/bus/agents", []string{}, false},
	OpBusListBusApprovals:                 {"GET", "/v1/bus/approvals/{namespace}/{tenant}", []string{"namespace", "tenant"}, false},
	OpBusListConversations:                {"GET", "/v1/bus/conversations", []string{}, false},
	OpBusListSchemas:                      {"GET", "/v1/bus/schemas", []string{}, false},
	OpBusListSubscriptions:                {"GET", "/v1/bus/subscriptions", []string{}, false},
	OpBusListTopics:                       {"GET", "/v1/bus/topics", []string{}, false},
	OpBusLookupToolResult:                 {"GET", "/v1/bus/tool-calls/{namespace}/{tenant}/{call_id}/result", []string{"namespace", "tenant", "call_id"}, false},
	OpBusPostStreamChunk:                  {"POST", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/stream-chunks", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusPostStreamEnd:                    {"POST", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/stream-end", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusPostToolCall:                     {"POST", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/tool-calls", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusPostToolResult:                   {"POST", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/tool-results", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusPublish:                          {"POST", "/v1/bus/publish", []string{}, false},
	OpBusRegisterAgent:                    {"POST", "/v1/bus/agents", []string{}, false},
	OpBusRegisterConversation:             {"POST", "/v1/bus/conversations", []string{}, false},
	OpBusRejectBusApproval:                {"POST", "/v1/bus/approvals/{namespace}/{tenant}/{approval_id}/reject", []string{"namespace", "tenant", "approval_id"}, false},
	OpBusReplayConversationMessages:       {"GET", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/messages", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusSendToAgent:                      {"POST", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/send", []string{"namespace", "tenant", "agent_id"}, false},
	OpBusSessionsAck:                      {"POST", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}/ack", []string{"namespace", "tenant", "id", "session"}, false},
	OpBusSessionsClose:                    {"DELETE", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}", []string{"namespace", "tenant", "id", "session"}, false},
	OpBusSessionsGet:                      {"GET", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}", []string{"namespace", "tenant", "id", "session"}, false},
	OpBusSessionsOpen:                     {"POST", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions", []string{"namespace", "tenant", "id"}, false},
	OpBusSessionsReceive:                  {"POST", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}/receive", []string{"namespace", "tenant", "id", "session"}, false},
	OpBusSessionsValidate:                 {"POST", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}/validate", []string{"namespace", "tenant", "id", "session"}, false},
	OpBusSetAgentAdminState:               {"PUT", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/admin-state", []string{"namespace", "tenant", "agent_id"}, false},
	OpBusStagesControl:                    {"POST", "/v1/bus/stages/{namespace}/{tenant}/{id}/control", []string{"namespace", "tenant", "id"}, false},
	OpBusStagesControlAudit:               {"GET", "/v1/bus/stages/{namespace}/{tenant}/{id}/controls/{request}", []string{"namespace", "tenant", "id", "request"}, false},
	OpBusStagesDiscard:                    {"DELETE", "/v1/bus/stages/{namespace}/{tenant}/{id}/quarantine/{entry}", []string{"namespace", "tenant", "id", "entry"}, false},
	OpBusStagesGet:                        {"GET", "/v1/bus/stages/{namespace}/{tenant}/{id}/quarantine/{entry}", []string{"namespace", "tenant", "id", "entry"}, false},
	OpBusStagesList:                       {"GET", "/v1/bus/stages/{namespace}/{tenant}/{id}/quarantine", []string{"namespace", "tenant", "id"}, false},
	OpBusStagesReplay:                     {"POST", "/v1/bus/stages/{namespace}/{tenant}/{id}/quarantine/{entry}/replay", []string{"namespace", "tenant", "id", "entry"}, false},
	OpBusStagesReplayAudit:                {"GET", "/v1/bus/stages/{namespace}/{tenant}/{id}/replays/{request}", []string{"namespace", "tenant", "id", "request"}, false},
	OpBusStagesStatus:                     {"GET", "/v1/bus/stages/{namespace}/{tenant}/{id}", []string{"namespace", "tenant", "id"}, false},
	OpBusSubscriptionLag:                  {"GET", "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/lag", []string{"namespace", "tenant", "id"}, false},
	OpBusTransitionConversation:           {"POST", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/transition", []string{"namespace", "tenant", "conversation_id"}, false},
	OpBusUnbindTopicSchema:                {"DELETE", "/v1/bus/topics/{namespace}/{tenant}/{name}/schema", []string{"namespace", "tenant", "name"}, false},
	OpBusUpdateAgent:                      {"PUT", "/v1/bus/agents/{namespace}/{tenant}/{agent_id}", []string{"namespace", "tenant", "agent_id"}, false},
	OpBusUpdateConversation:               {"PUT", "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}", []string{"namespace", "tenant", "conversation_id"}, false},
	OpChainsCancelChain:                   {"POST", "/v1/chains/{chain_id}/cancel", []string{"chain_id"}, false},
	OpChainsDeleteDefinition:              {"DELETE", "/v1/chains/definitions/{name}", []string{"name"}, false},
	OpChainsGetChain:                      {"GET", "/v1/chains/{chain_id}", []string{"chain_id"}, false},
	OpChainsGetChainDag:                   {"GET", "/v1/chains/{chain_id}/dag", []string{"chain_id"}, false},
	OpChainsGetChainDefinitionDag:         {"GET", "/v1/chains/definitions/{name}/dag", []string{"name"}, false},
	OpChainsGetChainHistory:               {"GET", "/v1/chains/{chain_id}/history", []string{"chain_id"}, false},
	OpChainsGetDefinition:                 {"GET", "/v1/chains/definitions/{name}", []string{"name"}, false},
	OpChainsListChains:                    {"GET", "/v1/chains", []string{}, false},
	OpChainsListDefinitions:               {"GET", "/v1/chains/definitions", []string{}, false},
	OpChainsPutDefinition:                 {"PUT", "/v1/chains/definitions/{name}", []string{"name"}, false},
	OpCircuitBreakersListCircuitBreakers:  {"GET", "/admin/circuit-breakers", []string{}, false},
	OpCircuitBreakersResetCircuitBreaker:  {"POST", "/admin/circuit-breakers/{provider}/reset", []string{"provider"}, false},
	OpCircuitBreakersTripCircuitBreaker:   {"POST", "/admin/circuit-breakers/{provider}/trip", []string{"provider"}, false},
	OpComplianceGetComplianceStatus:       {"GET", "/v1/compliance/status", []string{}, false},
	OpComplianceVerifyAuditChain:          {"POST", "/v1/audit/verify", []string{}, false},
	OpConfigGetConfig:                     {"GET", "/admin/config", []string{}, false},
	OpDispatchDispatch:                    {"POST", "/v1/dispatch", []string{}, false},
	OpDispatchDispatchBatch:               {"POST", "/v1/dispatch/batch", []string{}, false},
	OpDlqDlqDrain:                         {"POST", "/v1/dlq/drain", []string{}, false},
	OpDlqDlqStats:                         {"GET", "/v1/dlq/stats", []string{}, false},
	OpEmbeddingsSimilarity:                {"POST", "/v1/embeddings/similarity", []string{}, false},
	OpEventsGetEvent:                      {"GET", "/v1/events/{fingerprint}", []string{"fingerprint"}, false},
	OpEventsListEvents:                    {"GET", "/v1/events", []string{}, false},
	OpEventsTransitionEvent:               {"PUT", "/v1/events/{fingerprint}/transition", []string{"fingerprint"}, false},
	OpExecutionsGetExecution:              {"GET", "/v1/executions/{execution_id}", []string{"execution_id"}, false},
	OpExecutionsGetExecutionHistory:       {"GET", "/v1/executions/{execution_id}/history", []string{"execution_id"}, false},
	OpExecutionsListExecutions:            {"GET", "/v1/executions", []string{}, false},
	OpExecutionsResetExecution:            {"POST", "/v1/executions/{execution_id}/reset", []string{"execution_id"}, false},
	OpExecutionsSignalExecution:           {"POST", "/v1/executions/{execution_id}/signal/{signal_name}", []string{"execution_id", "signal_name"}, false},
	OpExecutionsUpsertExecutionAttributes: {"PUT", "/v1/executions/{execution_id}/attributes", []string{"execution_id"}, false},
	OpGovernanceInspect:                   {"GET", "/v1/governance", []string{}, false},
	OpGovernanceIntervene:                 {"POST", "/v1/governance/changes", []string{}, false},
	OpGovernancePublishPermit:             {"POST", "/v1/governance/permits", []string{}, false},
	OpGroupsFlushGroup:                    {"DELETE", "/v1/groups/{group_key}", []string{"group_key"}, false},
	OpGroupsGetGroup:                      {"GET", "/v1/groups/{group_key}", []string{"group_key"}, false},
	OpGroupsListGroups:                    {"GET", "/v1/groups", []string{}, false},
	OpHealthHealth:                        {"GET", "/health", []string{}, false},
	OpHealthMetrics:                       {"GET", "/metrics", []string{}, false},
	OpPluginsListPlugins:                  {"GET", "/v1/plugins", []string{}, false},
	OpPluginsUnregisterPlugin:             {"DELETE", "/v1/plugins/{name}", []string{"name"}, false},
	OpPrometheusPrometheusAlertRules:      {"GET", "/v1/metrics/alerts/prometheus.yaml", []string{}, true},
	OpPrometheusPrometheusMetrics:         {"GET", "/metrics/prometheus", []string{}, true},
	OpProviderHealthListProviderHealth:    {"GET", "/v1/providers/health", []string{}, false},
	OpQueuesCompleteTask:                  {"POST", "/v1/queues/tasks/{task_id}/complete", []string{"task_id"}, false},
	OpQueuesEnqueueTask:                   {"POST", "/v1/queues/{queue}/tasks", []string{"queue"}, false},
	OpQueuesFailTask:                      {"POST", "/v1/queues/tasks/{task_id}/fail", []string{"task_id"}, false},
	OpQueuesGetTask:                       {"GET", "/v1/queues/tasks/{task_id}", []string{"task_id"}, false},
	OpQueuesHeartbeatTask:                 {"POST", "/v1/queues/tasks/{task_id}/heartbeat", []string{"task_id"}, false},
	OpQueuesListTasks:                     {"GET", "/v1/queues/{queue}/tasks", []string{"queue"}, false},
	OpQueuesPollQueue:                     {"POST", "/v1/queues/{queue}/poll", []string{"queue"}, false},
	OpQuotasCreateQuota:                   {"POST", "/v1/quotas", []string{}, false},
	OpQuotasDeleteQuota:                   {"DELETE", "/v1/quotas/{id}", []string{"id"}, false},
	OpQuotasGetQuota:                      {"GET", "/v1/quotas/{id}", []string{"id"}, false},
	OpQuotasGetQuotaUsage:                 {"GET", "/v1/quotas/{id}/usage", []string{"id"}, false},
	OpQuotasListQuotas:                    {"GET", "/v1/quotas", []string{}, false},
	OpQuotasReloadStaticQuotas:            {"POST", "/v1/quotas/reload", []string{}, false},
	OpQuotasUpdateQuota:                   {"PUT", "/v1/quotas/{id}", []string{"id"}, false},
	OpRecurringBackfillRecurring:          {"POST", "/v1/recurring/{id}/backfill", []string{"id"}, false},
	OpRecurringCreateRecurring:            {"POST", "/v1/recurring", []string{}, false},
	OpRecurringDeleteRecurring:            {"DELETE", "/v1/recurring/{id}", []string{"id"}, false},
	OpRecurringGetRecurring:               {"GET", "/v1/recurring/{id}", []string{"id"}, false},
	OpRecurringListRecurring:              {"GET", "/v1/recurring", []string{}, false},
	OpRecurringPauseRecurring:             {"POST", "/v1/recurring/{id}/pause", []string{"id"}, false},
	OpRecurringResumeRecurring:            {"POST", "/v1/recurring/{id}/resume", []string{"id"}, false},
	OpRecurringUpdateRecurring:            {"PUT", "/v1/recurring/{id}", []string{"id"}, false},
	OpReplayReplayAction:                  {"POST", "/v1/audit/{action_id}/replay", []string{"action_id"}, false},
	OpReplayReplayAudit:                   {"POST", "/v1/audit/replay", []string{}, false},
	OpRetentionCreateRetention:            {"POST", "/v1/retention", []string{}, false},
	OpRetentionDeleteRetention:            {"DELETE", "/v1/retention/{id}", []string{"id"}, false},
	OpRetentionGetRetention:               {"GET", "/v1/retention/{id}", []string{"id"}, false},
	OpRetentionListRetention:              {"GET", "/v1/retention", []string{}, false},
	OpRetentionUpdateRetention:            {"PUT", "/v1/retention/{id}", []string{"id"}, false},
	OpRulesEvaluateRules:                  {"POST", "/v1/rules/evaluate", []string{}, false},
	OpRulesListRules:                      {"GET", "/v1/rules", []string{}, false},
	OpRulesReloadRules:                    {"POST", "/v1/rules/reload", []string{}, false},
	OpRulesRuleCoverage:                   {"GET", "/v1/rules/coverage", []string{}, false},
	OpRulesSetRuleEnabled:                 {"PUT", "/v1/rules/{name}/enabled", []string{"name"}, false},
	OpSigningKeysDiscoverSigningKeys:      {"GET", "/.well-known/acteon-signing-keys", []string{}, false},
	OpSilencesCreateSilence:               {"POST", "/v1/silences", []string{}, false},
	OpSilencesDeleteSilence:               {"DELETE", "/v1/silences/{id}", []string{"id"}, false},
	OpSilencesGetSilence:                  {"GET", "/v1/silences/{id}", []string{"id"}, false},
	OpSilencesListSilences:                {"GET", "/v1/silences", []string{}, false},
	OpSilencesUpdateSilence:               {"PUT", "/v1/silences/{id}", []string{"id"}, false},
	OpSwarmCancelSwarmRun:                 {"POST", "/v1/swarm/runs/{run_id}/cancel", []string{"run_id"}, false},
	OpSwarmGetSwarmRun:                    {"GET", "/v1/swarm/runs/{run_id}", []string{"run_id"}, false},
	OpSwarmListSwarmRuns:                  {"GET", "/v1/swarm/runs", []string{}, false},
	OpTemplatesCreateProfile:              {"POST", "/v1/templates/profiles", []string{}, false},
	OpTemplatesCreateTemplate:             {"POST", "/v1/templates", []string{}, false},
	OpTemplatesDeleteProfile:              {"DELETE", "/v1/templates/profiles/{id}", []string{"id"}, false},
	OpTemplatesDeleteTemplate:             {"DELETE", "/v1/templates/{id}", []string{"id"}, false},
	OpTemplatesGetProfile:                 {"GET", "/v1/templates/profiles/{id}", []string{"id"}, false},
	OpTemplatesGetTemplate:                {"GET", "/v1/templates/{id}", []string{"id"}, false},
	OpTemplatesListProfiles:               {"GET", "/v1/templates/profiles", []string{}, false},
	OpTemplatesListTemplates:              {"GET", "/v1/templates", []string{}, false},
	OpTemplatesReloadStaticTemplates:      {"POST", "/v1/templates/reload", []string{}, false},
	OpTemplatesRenderPreview:              {"POST", "/v1/templates/render", []string{}, false},
	OpTemplatesUpdateProfile:              {"PUT", "/v1/templates/profiles/{id}", []string{"id"}, false},
	OpTemplatesUpdateTemplate:             {"PUT", "/v1/templates/{id}", []string{"id"}, false},
	OpTimeIntervalsCreateTimeInterval:     {"POST", "/v1/time-intervals", []string{}, false},
	OpTimeIntervalsDeleteTimeInterval:     {"DELETE", "/v1/time-intervals/{namespace}/{tenant}/{name}", []string{"namespace", "tenant", "name"}, false},
	OpTimeIntervalsGetTimeInterval:        {"GET", "/v1/time-intervals/{namespace}/{tenant}/{name}", []string{"namespace", "tenant", "name"}, false},
	OpTimeIntervalsListTimeIntervals:      {"GET", "/v1/time-intervals", []string{}, false},
	OpTimeIntervalsUpdateTimeInterval:     {"PUT", "/v1/time-intervals/{namespace}/{tenant}/{name}", []string{"namespace", "tenant", "name"}, false},
	OpVerifyVerifyAction:                  {"GET", "/v1/actions/{id}/verify", []string{"id"}, false},
	OpWorkflowsCancelWorkflow:             {"POST", "/v1/workflows/executions/{execution_id}/cancel", []string{"execution_id"}, false},
	OpWorkflowsGetWorkflow:                {"GET", "/v1/workflows/executions/{execution_id}", []string{"execution_id"}, false},
	OpWorkflowsListWorkflows:              {"GET", "/v1/workflows/executions", []string{}, false},
	OpWorkflowsRecordCheckpoint:           {"POST", "/v1/workflows/executions/{execution_id}/checkpoints", []string{"execution_id"}, false},
	OpWorkflowsSignalWorkflow:             {"POST", "/v1/workflows/executions/{execution_id}/signal/{signal_name}", []string{"execution_id", "signal_name"}, false},
	OpWorkflowsStartChildWorkflow:         {"POST", "/v1/workflows/executions/{execution_id}/children", []string{"execution_id"}, false},
	OpWorkflowsStartWorkflow:              {"POST", "/v1/workflows/start", []string{}, false},
	OpWorkforceChange:                     {"POST", "/v1/workforce/changes", []string{}, false},
	OpWorkforceInspect:                    {"GET", "/v1/workforce", []string{}, false},
}
