# Generated by scripts/sdk/platform_catalog.py. Do not edit.
from enum import StrEnum


class PlatformOperation(StrEnum):
    A2A_A2A_REST_MESSAGE_SEND = "a2a_a2a_rest_message_send"
    A2A_A2A_REST_TASK_CANCEL = "a2a_a2a_rest_task_cancel"
    A2A_A2A_REST_TASK_GET = "a2a_a2a_rest_task_get"
    A2A_DISCOVERY_DELETE_AGENT_CARD = "a2a_discovery_delete_agent_card"
    A2A_DISCOVERY_DISCOVER_AGENT = "a2a_discovery_discover_agent"
    A2A_DISCOVERY_GET_AGENT_CARD = "a2a_discovery_get_agent_card"
    A2A_DISCOVERY_PUT_AGENT_CARD = "a2a_discovery_put_agent_card"
    A2A_PUSH_REST_DELETE_PUSH_CONFIG = "a2a_push_rest_delete_push_config"
    A2A_PUSH_REST_DELETE_PUSH_DLQ = "a2a_push_rest_delete_push_dlq"
    A2A_PUSH_REST_GET_PUSH_CONFIG = "a2a_push_rest_get_push_config"
    A2A_PUSH_REST_GET_PUSH_DLQ = "a2a_push_rest_get_push_dlq"
    A2A_PUSH_REST_LIST_PUSH_CONFIGS = "a2a_push_rest_list_push_configs"
    A2A_PUSH_REST_LIST_PUSH_DLQ = "a2a_push_rest_list_push_dlq"
    A2A_PUSH_REST_SET_PUSH_CONFIG = "a2a_push_rest_set_push_config"
    AGENT_SERVICES_MESSAGE_SEND = "agent_services_message_send"
    AGENT_SERVICES_TASK_GET = "agent_services_task_get"
    ANALYTICS_QUERY_ANALYTICS = "analytics_query_analytics"
    APPROVALS_APPROVE = "approvals_approve"
    APPROVALS_GET_APPROVAL = "approvals_get_approval"
    APPROVALS_LIST_APPROVALS = "approvals_list_approvals"
    APPROVALS_REJECT = "approvals_reject"
    AUDIT_GET_AUDIT_BY_ACTION = "audit_get_audit_by_action"
    AUDIT_QUERY_AUDIT = "audit_query_audit"
    AUTH_IDENTITY = "auth_identity"
    AUTH_LOGIN = "auth_login"
    AUTH_LOGOUT = "auth_logout"
    BUS_ACK_SUBSCRIPTION = "bus_ack_subscription"
    BUS_APPEND_CONVERSATION_MESSAGE = "bus_append_conversation_message"
    BUS_APPROVE_BUS_APPROVAL = "bus_approve_bus_approval"
    BUS_BIND_TOPIC_SCHEMA = "bus_bind_topic_schema"
    BUS_CREATE_SCHEMA = "bus_create_schema"
    BUS_CREATE_SUBSCRIPTION = "bus_create_subscription"
    BUS_CREATE_TOPIC = "bus_create_topic"
    BUS_DEADLETTER_SUBSCRIPTION = "bus_deadletter_subscription"
    BUS_DELETE_AGENT = "bus_delete_agent"
    BUS_DELETE_CONVERSATION = "bus_delete_conversation"
    BUS_DELETE_SCHEMA_VERSION = "bus_delete_schema_version"
    BUS_DELETE_SUBSCRIPTION = "bus_delete_subscription"
    BUS_DELETE_TOPIC = "bus_delete_topic"
    BUS_GET_AGENT = "bus_get_agent"
    BUS_GET_BUS_APPROVAL = "bus_get_bus_approval"
    BUS_GET_CONVERSATION = "bus_get_conversation"
    BUS_GET_SCHEMA_VERSION = "bus_get_schema_version"
    BUS_GET_SUBJECT_VERSIONS = "bus_get_subject_versions"
    BUS_HEARTBEAT_AGENT = "bus_heartbeat_agent"
    BUS_LIST_AGENTS = "bus_list_agents"
    BUS_LIST_BUS_APPROVALS = "bus_list_bus_approvals"
    BUS_LIST_CONVERSATIONS = "bus_list_conversations"
    BUS_LIST_SCHEMAS = "bus_list_schemas"
    BUS_LIST_SUBSCRIPTIONS = "bus_list_subscriptions"
    BUS_LIST_TOPICS = "bus_list_topics"
    BUS_LOOKUP_TOOL_RESULT = "bus_lookup_tool_result"
    BUS_POST_STREAM_CHUNK = "bus_post_stream_chunk"
    BUS_POST_STREAM_END = "bus_post_stream_end"
    BUS_POST_TOOL_CALL = "bus_post_tool_call"
    BUS_POST_TOOL_RESULT = "bus_post_tool_result"
    BUS_PUBLISH = "bus_publish"
    BUS_REGISTER_AGENT = "bus_register_agent"
    BUS_REGISTER_CONVERSATION = "bus_register_conversation"
    BUS_REJECT_BUS_APPROVAL = "bus_reject_bus_approval"
    BUS_REPLAY_CONVERSATION_MESSAGES = "bus_replay_conversation_messages"
    BUS_SEND_TO_AGENT = "bus_send_to_agent"
    BUS_SESSIONS_ACK = "bus_sessions_ack"
    BUS_SESSIONS_CLOSE = "bus_sessions_close"
    BUS_SESSIONS_GET = "bus_sessions_get"
    BUS_SESSIONS_OPEN = "bus_sessions_open"
    BUS_SESSIONS_RECEIVE = "bus_sessions_receive"
    BUS_SESSIONS_VALIDATE = "bus_sessions_validate"
    BUS_SET_AGENT_ADMIN_STATE = "bus_set_agent_admin_state"
    BUS_STAGES_CONTROL = "bus_stages_control"
    BUS_STAGES_CONTROL_AUDIT = "bus_stages_control_audit"
    BUS_STAGES_DISCARD = "bus_stages_discard"
    BUS_STAGES_GET = "bus_stages_get"
    BUS_STAGES_LIST = "bus_stages_list"
    BUS_STAGES_REPLAY = "bus_stages_replay"
    BUS_STAGES_REPLAY_AUDIT = "bus_stages_replay_audit"
    BUS_STAGES_STATUS = "bus_stages_status"
    BUS_SUBSCRIPTION_LAG = "bus_subscription_lag"
    BUS_TRANSITION_CONVERSATION = "bus_transition_conversation"
    BUS_UNBIND_TOPIC_SCHEMA = "bus_unbind_topic_schema"
    BUS_UPDATE_AGENT = "bus_update_agent"
    BUS_UPDATE_CONVERSATION = "bus_update_conversation"
    CHAINS_CANCEL_CHAIN = "chains_cancel_chain"
    CHAINS_DELETE_DEFINITION = "chains_delete_definition"
    CHAINS_GET_CHAIN = "chains_get_chain"
    CHAINS_GET_CHAIN_DAG = "chains_get_chain_dag"
    CHAINS_GET_CHAIN_DEFINITION_DAG = "chains_get_chain_definition_dag"
    CHAINS_GET_CHAIN_HISTORY = "chains_get_chain_history"
    CHAINS_GET_DEFINITION = "chains_get_definition"
    CHAINS_LIST_CHAINS = "chains_list_chains"
    CHAINS_LIST_DEFINITIONS = "chains_list_definitions"
    CHAINS_PUT_DEFINITION = "chains_put_definition"
    CIRCUIT_BREAKERS_LIST_CIRCUIT_BREAKERS = "circuit_breakers_list_circuit_breakers"
    CIRCUIT_BREAKERS_RESET_CIRCUIT_BREAKER = "circuit_breakers_reset_circuit_breaker"
    CIRCUIT_BREAKERS_TRIP_CIRCUIT_BREAKER = "circuit_breakers_trip_circuit_breaker"
    COMPLIANCE_GET_COMPLIANCE_STATUS = "compliance_get_compliance_status"
    COMPLIANCE_VERIFY_AUDIT_CHAIN = "compliance_verify_audit_chain"
    CONFIG_GET_CONFIG = "config_get_config"
    DISPATCH_DISPATCH = "dispatch_dispatch"
    DISPATCH_DISPATCH_BATCH = "dispatch_dispatch_batch"
    DLQ_DLQ_DRAIN = "dlq_dlq_drain"
    DLQ_DLQ_STATS = "dlq_dlq_stats"
    EMBEDDINGS_SIMILARITY = "embeddings_similarity"
    EVENTS_GET_EVENT = "events_get_event"
    EVENTS_LIST_EVENTS = "events_list_events"
    EVENTS_TRANSITION_EVENT = "events_transition_event"
    EXECUTIONS_GET_EXECUTION = "executions_get_execution"
    EXECUTIONS_GET_EXECUTION_HISTORY = "executions_get_execution_history"
    EXECUTIONS_LIST_EXECUTIONS = "executions_list_executions"
    EXECUTIONS_RESET_EXECUTION = "executions_reset_execution"
    EXECUTIONS_SIGNAL_EXECUTION = "executions_signal_execution"
    EXECUTIONS_UPSERT_EXECUTION_ATTRIBUTES = "executions_upsert_execution_attributes"
    GOVERNANCE_ACCEPT_RECONCILIATION = "governance_accept_reconciliation"
    GOVERNANCE_INSPECT = "governance_inspect"
    GOVERNANCE_INTERVENE = "governance_intervene"
    GOVERNANCE_PROVIDER_HISTORY = "governance_provider_history"
    GOVERNANCE_PUBLISH_PERMIT = "governance_publish_permit"
    GOVERNANCE_RECONCILIATION_CORRELATION = "governance_reconciliation_correlation"
    GROUPS_FLUSH_GROUP = "groups_flush_group"
    GROUPS_GET_GROUP = "groups_get_group"
    GROUPS_LIST_GROUPS = "groups_list_groups"
    HEALTH_HEALTH = "health_health"
    HEALTH_METRICS = "health_metrics"
    PLUGINS_LIST_PLUGINS = "plugins_list_plugins"
    PLUGINS_UNREGISTER_PLUGIN = "plugins_unregister_plugin"
    PROMETHEUS_PROMETHEUS_ALERT_RULES = "prometheus_prometheus_alert_rules"
    PROMETHEUS_PROMETHEUS_METRICS = "prometheus_prometheus_metrics"
    PROVIDER_HEALTH_LIST_PROVIDER_HEALTH = "provider_health_list_provider_health"
    QUEUES_COMPLETE_TASK = "queues_complete_task"
    QUEUES_ENQUEUE_TASK = "queues_enqueue_task"
    QUEUES_FAIL_TASK = "queues_fail_task"
    QUEUES_GET_TASK = "queues_get_task"
    QUEUES_HEARTBEAT_TASK = "queues_heartbeat_task"
    QUEUES_LIST_TASKS = "queues_list_tasks"
    QUEUES_POLL_QUEUE = "queues_poll_queue"
    QUOTAS_CREATE_QUOTA = "quotas_create_quota"
    QUOTAS_DELETE_QUOTA = "quotas_delete_quota"
    QUOTAS_GET_QUOTA = "quotas_get_quota"
    QUOTAS_GET_QUOTA_USAGE = "quotas_get_quota_usage"
    QUOTAS_LIST_QUOTAS = "quotas_list_quotas"
    QUOTAS_RELOAD_STATIC_QUOTAS = "quotas_reload_static_quotas"
    QUOTAS_UPDATE_QUOTA = "quotas_update_quota"
    RECURRING_BACKFILL_RECURRING = "recurring_backfill_recurring"
    RECURRING_CREATE_RECURRING = "recurring_create_recurring"
    RECURRING_DELETE_RECURRING = "recurring_delete_recurring"
    RECURRING_GET_RECURRING = "recurring_get_recurring"
    RECURRING_LIST_RECURRING = "recurring_list_recurring"
    RECURRING_PAUSE_RECURRING = "recurring_pause_recurring"
    RECURRING_RESUME_RECURRING = "recurring_resume_recurring"
    RECURRING_UPDATE_RECURRING = "recurring_update_recurring"
    REPLAY_REPLAY_ACTION = "replay_replay_action"
    REPLAY_REPLAY_AUDIT = "replay_replay_audit"
    RETENTION_CREATE_RETENTION = "retention_create_retention"
    RETENTION_DELETE_RETENTION = "retention_delete_retention"
    RETENTION_GET_RETENTION = "retention_get_retention"
    RETENTION_LIST_RETENTION = "retention_list_retention"
    RETENTION_UPDATE_RETENTION = "retention_update_retention"
    RULES_EVALUATE_RULES = "rules_evaluate_rules"
    RULES_LIST_RULES = "rules_list_rules"
    RULES_RELOAD_RULES = "rules_reload_rules"
    RULES_RULE_COVERAGE = "rules_rule_coverage"
    RULES_SET_RULE_ENABLED = "rules_set_rule_enabled"
    SIGNING_KEYS_DISCOVER_SIGNING_KEYS = "signing_keys_discover_signing_keys"
    SILENCES_CREATE_SILENCE = "silences_create_silence"
    SILENCES_DELETE_SILENCE = "silences_delete_silence"
    SILENCES_GET_SILENCE = "silences_get_silence"
    SILENCES_LIST_SILENCES = "silences_list_silences"
    SILENCES_UPDATE_SILENCE = "silences_update_silence"
    SWARM_CANCEL_SWARM_RUN = "swarm_cancel_swarm_run"
    SWARM_GET_SWARM_RUN = "swarm_get_swarm_run"
    SWARM_LIST_SWARM_RUNS = "swarm_list_swarm_runs"
    TEMPLATES_CREATE_PROFILE = "templates_create_profile"
    TEMPLATES_CREATE_TEMPLATE = "templates_create_template"
    TEMPLATES_DELETE_PROFILE = "templates_delete_profile"
    TEMPLATES_DELETE_TEMPLATE = "templates_delete_template"
    TEMPLATES_GET_PROFILE = "templates_get_profile"
    TEMPLATES_GET_TEMPLATE = "templates_get_template"
    TEMPLATES_LIST_PROFILES = "templates_list_profiles"
    TEMPLATES_LIST_TEMPLATES = "templates_list_templates"
    TEMPLATES_RELOAD_STATIC_TEMPLATES = "templates_reload_static_templates"
    TEMPLATES_RENDER_PREVIEW = "templates_render_preview"
    TEMPLATES_UPDATE_PROFILE = "templates_update_profile"
    TEMPLATES_UPDATE_TEMPLATE = "templates_update_template"
    TIME_INTERVALS_CREATE_TIME_INTERVAL = "time_intervals_create_time_interval"
    TIME_INTERVALS_DELETE_TIME_INTERVAL = "time_intervals_delete_time_interval"
    TIME_INTERVALS_GET_TIME_INTERVAL = "time_intervals_get_time_interval"
    TIME_INTERVALS_LIST_TIME_INTERVALS = "time_intervals_list_time_intervals"
    TIME_INTERVALS_UPDATE_TIME_INTERVAL = "time_intervals_update_time_interval"
    VERIFY_VERIFY_ACTION = "verify_verify_action"
    WORKFLOWS_CANCEL_WORKFLOW = "workflows_cancel_workflow"
    WORKFLOWS_GET_WORKFLOW = "workflows_get_workflow"
    WORKFLOWS_LIST_WORKFLOWS = "workflows_list_workflows"
    WORKFLOWS_RECORD_CHECKPOINT = "workflows_record_checkpoint"
    WORKFLOWS_SIGNAL_WORKFLOW = "workflows_signal_workflow"
    WORKFLOWS_START_CHILD_WORKFLOW = "workflows_start_child_workflow"
    WORKFLOWS_START_WORKFLOW = "workflows_start_workflow"
    WORKFORCE_CHANGE = "workforce_change"
    WORKFORCE_INSPECT = "workforce_inspect"


OPERATIONS = {
    PlatformOperation.A2A_A2A_REST_MESSAGE_SEND: (
        "POST",
        "/a2a/{namespace}/{tenant}/v1/message:send",
        ("namespace", "tenant"),
        "json",
    ),
    PlatformOperation.A2A_A2A_REST_TASK_CANCEL: (
        "POST",
        "/a2a/{namespace}/{tenant}/v1/tasks/{id}",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.A2A_A2A_REST_TASK_GET: (
        "GET",
        "/a2a/{namespace}/{tenant}/v1/tasks/{id}",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.A2A_DISCOVERY_DELETE_AGENT_CARD: (
        "DELETE",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/card",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.A2A_DISCOVERY_DISCOVER_AGENT: (
        "GET",
        "/a2a/{namespace}/{tenant}/.well-known/agent.json",
        ("namespace", "tenant"),
        "json",
    ),
    PlatformOperation.A2A_DISCOVERY_GET_AGENT_CARD: (
        "GET",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/card",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.A2A_DISCOVERY_PUT_AGENT_CARD: (
        "PUT",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/card",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.A2A_PUSH_REST_DELETE_PUSH_CONFIG: (
        "DELETE",
        "/a2a/{namespace}/{tenant}/v1/tasks/{id}/pushNotificationConfigs/{cfgId}",
        ("namespace", "tenant", "id", "cfgId"),
        "json",
    ),
    PlatformOperation.A2A_PUSH_REST_DELETE_PUSH_DLQ: (
        "DELETE",
        "/v1/a2a/{namespace}/{tenant}/push-dlq/{entryId}",
        ("namespace", "tenant", "entryId"),
        "json",
    ),
    PlatformOperation.A2A_PUSH_REST_GET_PUSH_CONFIG: (
        "GET",
        "/a2a/{namespace}/{tenant}/v1/tasks/{id}/pushNotificationConfigs/{cfgId}",
        ("namespace", "tenant", "id", "cfgId"),
        "json",
    ),
    PlatformOperation.A2A_PUSH_REST_GET_PUSH_DLQ: (
        "GET",
        "/v1/a2a/{namespace}/{tenant}/push-dlq/{entryId}",
        ("namespace", "tenant", "entryId"),
        "json",
    ),
    PlatformOperation.A2A_PUSH_REST_LIST_PUSH_CONFIGS: (
        "GET",
        "/a2a/{namespace}/{tenant}/v1/tasks/{id}/pushNotificationConfigs",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.A2A_PUSH_REST_LIST_PUSH_DLQ: (
        "GET",
        "/v1/a2a/{namespace}/{tenant}/push-dlq",
        ("namespace", "tenant"),
        "json",
    ),
    PlatformOperation.A2A_PUSH_REST_SET_PUSH_CONFIG: (
        "POST",
        "/a2a/{namespace}/{tenant}/v1/tasks/{id}/pushNotificationConfigs",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.AGENT_SERVICES_MESSAGE_SEND: (
        "POST",
        "/a2a/{namespace}/{tenant}/agents/{agent}/v1/message:send",
        ("namespace", "tenant", "agent"),
        "json",
    ),
    PlatformOperation.AGENT_SERVICES_TASK_GET: (
        "GET",
        "/a2a/{namespace}/{tenant}/agents/{agent}/v1/tasks/{id}",
        ("namespace", "tenant", "agent", "id"),
        "json",
    ),
    PlatformOperation.ANALYTICS_QUERY_ANALYTICS: ("GET", "/v1/analytics", (), "json"),
    PlatformOperation.APPROVALS_APPROVE: (
        "POST",
        "/v1/approvals/{namespace}/{tenant}/{id}/approve",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.APPROVALS_GET_APPROVAL: (
        "GET",
        "/v1/approvals/{namespace}/{tenant}/{id}",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.APPROVALS_LIST_APPROVALS: ("GET", "/v1/approvals", (), "json"),
    PlatformOperation.APPROVALS_REJECT: (
        "POST",
        "/v1/approvals/{namespace}/{tenant}/{id}/reject",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.AUDIT_GET_AUDIT_BY_ACTION: (
        "GET",
        "/v1/audit/{action_id}",
        ("action_id",),
        "json",
    ),
    PlatformOperation.AUDIT_QUERY_AUDIT: ("GET", "/v1/audit", (), "json"),
    PlatformOperation.AUTH_IDENTITY: ("GET", "/v1/auth/identity", (), "json"),
    PlatformOperation.AUTH_LOGIN: ("POST", "/v1/auth/login", (), "json"),
    PlatformOperation.AUTH_LOGOUT: ("POST", "/v1/auth/logout", (), "json"),
    PlatformOperation.BUS_ACK_SUBSCRIPTION: (
        "POST",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/ack",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.BUS_APPEND_CONVERSATION_MESSAGE: (
        "POST",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/messages",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_APPROVE_BUS_APPROVAL: (
        "POST",
        "/v1/bus/approvals/{namespace}/{tenant}/{approval_id}/approve",
        ("namespace", "tenant", "approval_id"),
        "json",
    ),
    PlatformOperation.BUS_BIND_TOPIC_SCHEMA: (
        "PUT",
        "/v1/bus/topics/{namespace}/{tenant}/{name}/schema",
        ("namespace", "tenant", "name"),
        "json",
    ),
    PlatformOperation.BUS_CREATE_SCHEMA: ("POST", "/v1/bus/schemas", (), "json"),
    PlatformOperation.BUS_CREATE_SUBSCRIPTION: ("POST", "/v1/bus/subscriptions", (), "json"),
    PlatformOperation.BUS_CREATE_TOPIC: ("POST", "/v1/bus/topics", (), "json"),
    PlatformOperation.BUS_DEADLETTER_SUBSCRIPTION: (
        "POST",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/deadletter",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.BUS_DELETE_AGENT: (
        "DELETE",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.BUS_DELETE_CONVERSATION: (
        "DELETE",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_DELETE_SCHEMA_VERSION: (
        "DELETE",
        "/v1/bus/schemas/{namespace}/{tenant}/{subject}/{version}",
        ("namespace", "tenant", "subject", "version"),
        "json",
    ),
    PlatformOperation.BUS_DELETE_SUBSCRIPTION: (
        "DELETE",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.BUS_DELETE_TOPIC: (
        "DELETE",
        "/v1/bus/topics/{kafka_name}",
        ("kafka_name",),
        "json",
    ),
    PlatformOperation.BUS_GET_AGENT: (
        "GET",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.BUS_GET_BUS_APPROVAL: (
        "GET",
        "/v1/bus/approvals/{namespace}/{tenant}/{approval_id}",
        ("namespace", "tenant", "approval_id"),
        "json",
    ),
    PlatformOperation.BUS_GET_CONVERSATION: (
        "GET",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_GET_SCHEMA_VERSION: (
        "GET",
        "/v1/bus/schemas/{namespace}/{tenant}/{subject}/{version}",
        ("namespace", "tenant", "subject", "version"),
        "json",
    ),
    PlatformOperation.BUS_GET_SUBJECT_VERSIONS: (
        "GET",
        "/v1/bus/schemas/{namespace}/{tenant}/{subject}",
        ("namespace", "tenant", "subject"),
        "json",
    ),
    PlatformOperation.BUS_HEARTBEAT_AGENT: (
        "POST",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/heartbeat",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.BUS_LIST_AGENTS: ("GET", "/v1/bus/agents", (), "json"),
    PlatformOperation.BUS_LIST_BUS_APPROVALS: (
        "GET",
        "/v1/bus/approvals/{namespace}/{tenant}",
        ("namespace", "tenant"),
        "json",
    ),
    PlatformOperation.BUS_LIST_CONVERSATIONS: ("GET", "/v1/bus/conversations", (), "json"),
    PlatformOperation.BUS_LIST_SCHEMAS: ("GET", "/v1/bus/schemas", (), "json"),
    PlatformOperation.BUS_LIST_SUBSCRIPTIONS: ("GET", "/v1/bus/subscriptions", (), "json"),
    PlatformOperation.BUS_LIST_TOPICS: ("GET", "/v1/bus/topics", (), "json"),
    PlatformOperation.BUS_LOOKUP_TOOL_RESULT: (
        "GET",
        "/v1/bus/tool-calls/{namespace}/{tenant}/{call_id}/result",
        ("namespace", "tenant", "call_id"),
        "json",
    ),
    PlatformOperation.BUS_POST_STREAM_CHUNK: (
        "POST",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/stream-chunks",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_POST_STREAM_END: (
        "POST",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/stream-end",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_POST_TOOL_CALL: (
        "POST",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/tool-calls",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_POST_TOOL_RESULT: (
        "POST",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/tool-results",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_PUBLISH: ("POST", "/v1/bus/publish", (), "json"),
    PlatformOperation.BUS_REGISTER_AGENT: ("POST", "/v1/bus/agents", (), "json"),
    PlatformOperation.BUS_REGISTER_CONVERSATION: ("POST", "/v1/bus/conversations", (), "json"),
    PlatformOperation.BUS_REJECT_BUS_APPROVAL: (
        "POST",
        "/v1/bus/approvals/{namespace}/{tenant}/{approval_id}/reject",
        ("namespace", "tenant", "approval_id"),
        "json",
    ),
    PlatformOperation.BUS_REPLAY_CONVERSATION_MESSAGES: (
        "GET",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/messages",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_SEND_TO_AGENT: (
        "POST",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/send",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.BUS_SESSIONS_ACK: (
        "POST",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}/ack",
        ("namespace", "tenant", "id", "session"),
        "json",
    ),
    PlatformOperation.BUS_SESSIONS_CLOSE: (
        "DELETE",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}",
        ("namespace", "tenant", "id", "session"),
        "json",
    ),
    PlatformOperation.BUS_SESSIONS_GET: (
        "GET",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}",
        ("namespace", "tenant", "id", "session"),
        "json",
    ),
    PlatformOperation.BUS_SESSIONS_OPEN: (
        "POST",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.BUS_SESSIONS_RECEIVE: (
        "POST",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}/receive",
        ("namespace", "tenant", "id", "session"),
        "json",
    ),
    PlatformOperation.BUS_SESSIONS_VALIDATE: (
        "POST",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/sessions/{session}/validate",
        ("namespace", "tenant", "id", "session"),
        "json",
    ),
    PlatformOperation.BUS_SET_AGENT_ADMIN_STATE: (
        "PUT",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}/admin-state",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.BUS_STAGES_CONTROL: (
        "POST",
        "/v1/bus/stages/{namespace}/{tenant}/{id}/control",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.BUS_STAGES_CONTROL_AUDIT: (
        "GET",
        "/v1/bus/stages/{namespace}/{tenant}/{id}/controls/{request}",
        ("namespace", "tenant", "id", "request"),
        "json",
    ),
    PlatformOperation.BUS_STAGES_DISCARD: (
        "DELETE",
        "/v1/bus/stages/{namespace}/{tenant}/{id}/quarantine/{entry}",
        ("namespace", "tenant", "id", "entry"),
        "json",
    ),
    PlatformOperation.BUS_STAGES_GET: (
        "GET",
        "/v1/bus/stages/{namespace}/{tenant}/{id}/quarantine/{entry}",
        ("namespace", "tenant", "id", "entry"),
        "json",
    ),
    PlatformOperation.BUS_STAGES_LIST: (
        "GET",
        "/v1/bus/stages/{namespace}/{tenant}/{id}/quarantine",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.BUS_STAGES_REPLAY: (
        "POST",
        "/v1/bus/stages/{namespace}/{tenant}/{id}/quarantine/{entry}/replay",
        ("namespace", "tenant", "id", "entry"),
        "json",
    ),
    PlatformOperation.BUS_STAGES_REPLAY_AUDIT: (
        "GET",
        "/v1/bus/stages/{namespace}/{tenant}/{id}/replays/{request}",
        ("namespace", "tenant", "id", "request"),
        "json",
    ),
    PlatformOperation.BUS_STAGES_STATUS: (
        "GET",
        "/v1/bus/stages/{namespace}/{tenant}/{id}",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.BUS_SUBSCRIPTION_LAG: (
        "GET",
        "/v1/bus/subscriptions/{namespace}/{tenant}/{id}/lag",
        ("namespace", "tenant", "id"),
        "json",
    ),
    PlatformOperation.BUS_TRANSITION_CONVERSATION: (
        "POST",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}/transition",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.BUS_UNBIND_TOPIC_SCHEMA: (
        "DELETE",
        "/v1/bus/topics/{namespace}/{tenant}/{name}/schema",
        ("namespace", "tenant", "name"),
        "json",
    ),
    PlatformOperation.BUS_UPDATE_AGENT: (
        "PUT",
        "/v1/bus/agents/{namespace}/{tenant}/{agent_id}",
        ("namespace", "tenant", "agent_id"),
        "json",
    ),
    PlatformOperation.BUS_UPDATE_CONVERSATION: (
        "PUT",
        "/v1/bus/conversations/{namespace}/{tenant}/{conversation_id}",
        ("namespace", "tenant", "conversation_id"),
        "json",
    ),
    PlatformOperation.CHAINS_CANCEL_CHAIN: (
        "POST",
        "/v1/chains/{chain_id}/cancel",
        ("chain_id",),
        "json",
    ),
    PlatformOperation.CHAINS_DELETE_DEFINITION: (
        "DELETE",
        "/v1/chains/definitions/{name}",
        ("name",),
        "json",
    ),
    PlatformOperation.CHAINS_GET_CHAIN: ("GET", "/v1/chains/{chain_id}", ("chain_id",), "json"),
    PlatformOperation.CHAINS_GET_CHAIN_DAG: (
        "GET",
        "/v1/chains/{chain_id}/dag",
        ("chain_id",),
        "json",
    ),
    PlatformOperation.CHAINS_GET_CHAIN_DEFINITION_DAG: (
        "GET",
        "/v1/chains/definitions/{name}/dag",
        ("name",),
        "json",
    ),
    PlatformOperation.CHAINS_GET_CHAIN_HISTORY: (
        "GET",
        "/v1/chains/{chain_id}/history",
        ("chain_id",),
        "json",
    ),
    PlatformOperation.CHAINS_GET_DEFINITION: (
        "GET",
        "/v1/chains/definitions/{name}",
        ("name",),
        "json",
    ),
    PlatformOperation.CHAINS_LIST_CHAINS: ("GET", "/v1/chains", (), "json"),
    PlatformOperation.CHAINS_LIST_DEFINITIONS: ("GET", "/v1/chains/definitions", (), "json"),
    PlatformOperation.CHAINS_PUT_DEFINITION: (
        "PUT",
        "/v1/chains/definitions/{name}",
        ("name",),
        "json",
    ),
    PlatformOperation.CIRCUIT_BREAKERS_LIST_CIRCUIT_BREAKERS: (
        "GET",
        "/admin/circuit-breakers",
        (),
        "json",
    ),
    PlatformOperation.CIRCUIT_BREAKERS_RESET_CIRCUIT_BREAKER: (
        "POST",
        "/admin/circuit-breakers/{provider}/reset",
        ("provider",),
        "json",
    ),
    PlatformOperation.CIRCUIT_BREAKERS_TRIP_CIRCUIT_BREAKER: (
        "POST",
        "/admin/circuit-breakers/{provider}/trip",
        ("provider",),
        "json",
    ),
    PlatformOperation.COMPLIANCE_GET_COMPLIANCE_STATUS: (
        "GET",
        "/v1/compliance/status",
        (),
        "json",
    ),
    PlatformOperation.COMPLIANCE_VERIFY_AUDIT_CHAIN: ("POST", "/v1/audit/verify", (), "json"),
    PlatformOperation.CONFIG_GET_CONFIG: ("GET", "/admin/config", (), "json"),
    PlatformOperation.DISPATCH_DISPATCH: ("POST", "/v1/dispatch", (), "json"),
    PlatformOperation.DISPATCH_DISPATCH_BATCH: ("POST", "/v1/dispatch/batch", (), "json"),
    PlatformOperation.DLQ_DLQ_DRAIN: ("POST", "/v1/dlq/drain", (), "json"),
    PlatformOperation.DLQ_DLQ_STATS: ("GET", "/v1/dlq/stats", (), "json"),
    PlatformOperation.EMBEDDINGS_SIMILARITY: ("POST", "/v1/embeddings/similarity", (), "json"),
    PlatformOperation.EVENTS_GET_EVENT: (
        "GET",
        "/v1/events/{fingerprint}",
        ("fingerprint",),
        "json",
    ),
    PlatformOperation.EVENTS_LIST_EVENTS: ("GET", "/v1/events", (), "json"),
    PlatformOperation.EVENTS_TRANSITION_EVENT: (
        "PUT",
        "/v1/events/{fingerprint}/transition",
        ("fingerprint",),
        "json",
    ),
    PlatformOperation.EXECUTIONS_GET_EXECUTION: (
        "GET",
        "/v1/executions/{execution_id}",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.EXECUTIONS_GET_EXECUTION_HISTORY: (
        "GET",
        "/v1/executions/{execution_id}/history",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.EXECUTIONS_LIST_EXECUTIONS: ("GET", "/v1/executions", (), "json"),
    PlatformOperation.EXECUTIONS_RESET_EXECUTION: (
        "POST",
        "/v1/executions/{execution_id}/reset",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.EXECUTIONS_SIGNAL_EXECUTION: (
        "POST",
        "/v1/executions/{execution_id}/signal/{signal_name}",
        ("execution_id", "signal_name"),
        "json",
    ),
    PlatformOperation.EXECUTIONS_UPSERT_EXECUTION_ATTRIBUTES: (
        "PUT",
        "/v1/executions/{execution_id}/attributes",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.GOVERNANCE_ACCEPT_RECONCILIATION: (
        "POST",
        "/v1/governance/executions/{execution_id}/attempts/{ordinal}/reconciliation",
        ("execution_id", "ordinal"),
        "json",
    ),
    PlatformOperation.GOVERNANCE_INSPECT: ("GET", "/v1/governance", (), "json"),
    PlatformOperation.GOVERNANCE_INTERVENE: ("POST", "/v1/governance/changes", (), "json"),
    PlatformOperation.GOVERNANCE_PROVIDER_HISTORY: (
        "GET",
        "/v1/governance/executions/{execution_id}",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.GOVERNANCE_PUBLISH_PERMIT: ("POST", "/v1/governance/permits", (), "json"),
    PlatformOperation.GOVERNANCE_RECONCILIATION_CORRELATION: (
        "GET",
        "/v1/governance/executions/{execution_id}/attempts/{ordinal}/correlation",
        ("execution_id", "ordinal"),
        "json",
    ),
    PlatformOperation.GROUPS_FLUSH_GROUP: (
        "DELETE",
        "/v1/groups/{group_key}",
        ("group_key",),
        "json",
    ),
    PlatformOperation.GROUPS_GET_GROUP: ("GET", "/v1/groups/{group_key}", ("group_key",), "json"),
    PlatformOperation.GROUPS_LIST_GROUPS: ("GET", "/v1/groups", (), "json"),
    PlatformOperation.HEALTH_HEALTH: ("GET", "/health", (), "json"),
    PlatformOperation.HEALTH_METRICS: ("GET", "/metrics", (), "json"),
    PlatformOperation.PLUGINS_LIST_PLUGINS: ("GET", "/v1/plugins", (), "json"),
    PlatformOperation.PLUGINS_UNREGISTER_PLUGIN: (
        "DELETE",
        "/v1/plugins/{name}",
        ("name",),
        "json",
    ),
    PlatformOperation.PROMETHEUS_PROMETHEUS_ALERT_RULES: (
        "GET",
        "/v1/metrics/alerts/prometheus.yaml",
        (),
        "text",
    ),
    PlatformOperation.PROMETHEUS_PROMETHEUS_METRICS: ("GET", "/metrics/prometheus", (), "text"),
    PlatformOperation.PROVIDER_HEALTH_LIST_PROVIDER_HEALTH: (
        "GET",
        "/v1/providers/health",
        (),
        "json",
    ),
    PlatformOperation.QUEUES_COMPLETE_TASK: (
        "POST",
        "/v1/queues/tasks/{task_id}/complete",
        ("task_id",),
        "json",
    ),
    PlatformOperation.QUEUES_ENQUEUE_TASK: ("POST", "/v1/queues/{queue}/tasks", ("queue",), "json"),
    PlatformOperation.QUEUES_FAIL_TASK: (
        "POST",
        "/v1/queues/tasks/{task_id}/fail",
        ("task_id",),
        "json",
    ),
    PlatformOperation.QUEUES_GET_TASK: ("GET", "/v1/queues/tasks/{task_id}", ("task_id",), "json"),
    PlatformOperation.QUEUES_HEARTBEAT_TASK: (
        "POST",
        "/v1/queues/tasks/{task_id}/heartbeat",
        ("task_id",),
        "json",
    ),
    PlatformOperation.QUEUES_LIST_TASKS: ("GET", "/v1/queues/{queue}/tasks", ("queue",), "json"),
    PlatformOperation.QUEUES_POLL_QUEUE: ("POST", "/v1/queues/{queue}/poll", ("queue",), "json"),
    PlatformOperation.QUOTAS_CREATE_QUOTA: ("POST", "/v1/quotas", (), "json"),
    PlatformOperation.QUOTAS_DELETE_QUOTA: ("DELETE", "/v1/quotas/{id}", ("id",), "json"),
    PlatformOperation.QUOTAS_GET_QUOTA: ("GET", "/v1/quotas/{id}", ("id",), "json"),
    PlatformOperation.QUOTAS_GET_QUOTA_USAGE: ("GET", "/v1/quotas/{id}/usage", ("id",), "json"),
    PlatformOperation.QUOTAS_LIST_QUOTAS: ("GET", "/v1/quotas", (), "json"),
    PlatformOperation.QUOTAS_RELOAD_STATIC_QUOTAS: ("POST", "/v1/quotas/reload", (), "json"),
    PlatformOperation.QUOTAS_UPDATE_QUOTA: ("PUT", "/v1/quotas/{id}", ("id",), "json"),
    PlatformOperation.RECURRING_BACKFILL_RECURRING: (
        "POST",
        "/v1/recurring/{id}/backfill",
        ("id",),
        "json",
    ),
    PlatformOperation.RECURRING_CREATE_RECURRING: ("POST", "/v1/recurring", (), "json"),
    PlatformOperation.RECURRING_DELETE_RECURRING: ("DELETE", "/v1/recurring/{id}", ("id",), "json"),
    PlatformOperation.RECURRING_GET_RECURRING: ("GET", "/v1/recurring/{id}", ("id",), "json"),
    PlatformOperation.RECURRING_LIST_RECURRING: ("GET", "/v1/recurring", (), "json"),
    PlatformOperation.RECURRING_PAUSE_RECURRING: (
        "POST",
        "/v1/recurring/{id}/pause",
        ("id",),
        "json",
    ),
    PlatformOperation.RECURRING_RESUME_RECURRING: (
        "POST",
        "/v1/recurring/{id}/resume",
        ("id",),
        "json",
    ),
    PlatformOperation.RECURRING_UPDATE_RECURRING: ("PUT", "/v1/recurring/{id}", ("id",), "json"),
    PlatformOperation.REPLAY_REPLAY_ACTION: (
        "POST",
        "/v1/audit/{action_id}/replay",
        ("action_id",),
        "json",
    ),
    PlatformOperation.REPLAY_REPLAY_AUDIT: ("POST", "/v1/audit/replay", (), "json"),
    PlatformOperation.RETENTION_CREATE_RETENTION: ("POST", "/v1/retention", (), "json"),
    PlatformOperation.RETENTION_DELETE_RETENTION: ("DELETE", "/v1/retention/{id}", ("id",), "json"),
    PlatformOperation.RETENTION_GET_RETENTION: ("GET", "/v1/retention/{id}", ("id",), "json"),
    PlatformOperation.RETENTION_LIST_RETENTION: ("GET", "/v1/retention", (), "json"),
    PlatformOperation.RETENTION_UPDATE_RETENTION: ("PUT", "/v1/retention/{id}", ("id",), "json"),
    PlatformOperation.RULES_EVALUATE_RULES: ("POST", "/v1/rules/evaluate", (), "json"),
    PlatformOperation.RULES_LIST_RULES: ("GET", "/v1/rules", (), "json"),
    PlatformOperation.RULES_RELOAD_RULES: ("POST", "/v1/rules/reload", (), "json"),
    PlatformOperation.RULES_RULE_COVERAGE: ("GET", "/v1/rules/coverage", (), "json"),
    PlatformOperation.RULES_SET_RULE_ENABLED: (
        "PUT",
        "/v1/rules/{name}/enabled",
        ("name",),
        "json",
    ),
    PlatformOperation.SIGNING_KEYS_DISCOVER_SIGNING_KEYS: (
        "GET",
        "/.well-known/acteon-signing-keys",
        (),
        "json",
    ),
    PlatformOperation.SILENCES_CREATE_SILENCE: ("POST", "/v1/silences", (), "json"),
    PlatformOperation.SILENCES_DELETE_SILENCE: ("DELETE", "/v1/silences/{id}", ("id",), "json"),
    PlatformOperation.SILENCES_GET_SILENCE: ("GET", "/v1/silences/{id}", ("id",), "json"),
    PlatformOperation.SILENCES_LIST_SILENCES: ("GET", "/v1/silences", (), "json"),
    PlatformOperation.SILENCES_UPDATE_SILENCE: ("PUT", "/v1/silences/{id}", ("id",), "json"),
    PlatformOperation.SWARM_CANCEL_SWARM_RUN: (
        "POST",
        "/v1/swarm/runs/{run_id}/cancel",
        ("run_id",),
        "json",
    ),
    PlatformOperation.SWARM_GET_SWARM_RUN: ("GET", "/v1/swarm/runs/{run_id}", ("run_id",), "json"),
    PlatformOperation.SWARM_LIST_SWARM_RUNS: ("GET", "/v1/swarm/runs", (), "json"),
    PlatformOperation.TEMPLATES_CREATE_PROFILE: ("POST", "/v1/templates/profiles", (), "json"),
    PlatformOperation.TEMPLATES_CREATE_TEMPLATE: ("POST", "/v1/templates", (), "json"),
    PlatformOperation.TEMPLATES_DELETE_PROFILE: (
        "DELETE",
        "/v1/templates/profiles/{id}",
        ("id",),
        "json",
    ),
    PlatformOperation.TEMPLATES_DELETE_TEMPLATE: ("DELETE", "/v1/templates/{id}", ("id",), "json"),
    PlatformOperation.TEMPLATES_GET_PROFILE: (
        "GET",
        "/v1/templates/profiles/{id}",
        ("id",),
        "json",
    ),
    PlatformOperation.TEMPLATES_GET_TEMPLATE: ("GET", "/v1/templates/{id}", ("id",), "json"),
    PlatformOperation.TEMPLATES_LIST_PROFILES: ("GET", "/v1/templates/profiles", (), "json"),
    PlatformOperation.TEMPLATES_LIST_TEMPLATES: ("GET", "/v1/templates", (), "json"),
    PlatformOperation.TEMPLATES_RELOAD_STATIC_TEMPLATES: (
        "POST",
        "/v1/templates/reload",
        (),
        "json",
    ),
    PlatformOperation.TEMPLATES_RENDER_PREVIEW: ("POST", "/v1/templates/render", (), "json"),
    PlatformOperation.TEMPLATES_UPDATE_PROFILE: (
        "PUT",
        "/v1/templates/profiles/{id}",
        ("id",),
        "json",
    ),
    PlatformOperation.TEMPLATES_UPDATE_TEMPLATE: ("PUT", "/v1/templates/{id}", ("id",), "json"),
    PlatformOperation.TIME_INTERVALS_CREATE_TIME_INTERVAL: (
        "POST",
        "/v1/time-intervals",
        (),
        "json",
    ),
    PlatformOperation.TIME_INTERVALS_DELETE_TIME_INTERVAL: (
        "DELETE",
        "/v1/time-intervals/{namespace}/{tenant}/{name}",
        ("namespace", "tenant", "name"),
        "json",
    ),
    PlatformOperation.TIME_INTERVALS_GET_TIME_INTERVAL: (
        "GET",
        "/v1/time-intervals/{namespace}/{tenant}/{name}",
        ("namespace", "tenant", "name"),
        "json",
    ),
    PlatformOperation.TIME_INTERVALS_LIST_TIME_INTERVALS: ("GET", "/v1/time-intervals", (), "json"),
    PlatformOperation.TIME_INTERVALS_UPDATE_TIME_INTERVAL: (
        "PUT",
        "/v1/time-intervals/{namespace}/{tenant}/{name}",
        ("namespace", "tenant", "name"),
        "json",
    ),
    PlatformOperation.VERIFY_VERIFY_ACTION: ("GET", "/v1/actions/{id}/verify", ("id",), "json"),
    PlatformOperation.WORKFLOWS_CANCEL_WORKFLOW: (
        "POST",
        "/v1/workflows/executions/{execution_id}/cancel",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.WORKFLOWS_GET_WORKFLOW: (
        "GET",
        "/v1/workflows/executions/{execution_id}",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.WORKFLOWS_LIST_WORKFLOWS: ("GET", "/v1/workflows/executions", (), "json"),
    PlatformOperation.WORKFLOWS_RECORD_CHECKPOINT: (
        "POST",
        "/v1/workflows/executions/{execution_id}/checkpoints",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.WORKFLOWS_SIGNAL_WORKFLOW: (
        "POST",
        "/v1/workflows/executions/{execution_id}/signal/{signal_name}",
        ("execution_id", "signal_name"),
        "json",
    ),
    PlatformOperation.WORKFLOWS_START_CHILD_WORKFLOW: (
        "POST",
        "/v1/workflows/executions/{execution_id}/children",
        ("execution_id",),
        "json",
    ),
    PlatformOperation.WORKFLOWS_START_WORKFLOW: ("POST", "/v1/workflows/start", (), "json"),
    PlatformOperation.WORKFORCE_CHANGE: ("POST", "/v1/workforce/changes", (), "json"),
    PlatformOperation.WORKFORCE_INSPECT: ("GET", "/v1/workforce", (), "json"),
}
